#!/usr/bin/env python3
"""Build a documentation-only evidence freeze; never fit a model or change source artifacts."""
from __future__ import annotations
import argparse, csv, hashlib, io, json, os, subprocess, sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
import numpy as np
import pandas as pd
import yaml
from sklearn.metrics import average_precision_score, roc_auc_score

ROOT = Path(__file__).resolve().parents[2]
os.chdir(ROOT)
CFG = Path('artifacts/thesis/documentation_build_config.json')
config = json.loads(CFG.read_text())
RUN = Path(config['run_dir'])
P = 'runs/phm2026_loeo_evaluation/20260912T110848985882Z-e1911d4f'
T = 'runs/phm2026_image_target/20260912T052857044116Z-c936a4e3'
S1 = 'runs/reassemble/20260927T154732Z-section1'
S1B = 'runs/reassemble/20260927T175336Z-section1b'
S2 = 'runs/reassemble/20260927T192852Z-section2'
PREFIX = 'runs/reassemble/20260927T204649Z-'
S3, DROP, AUDIO, EFF, OBJ, FINAL = [PREFIX+x for x in ['section3','modality-dropout','audio-gate','efficiency','object-feasibility','final-synthesis']]
EX = 'runs/reassemble/additional_improvements_executed/20260928T000346Z'
SOURCES = {
 'RQ':'docs/intel_welding/research_contract.md',
 'P_TARGET':'docs/thesis/TARGET_VERSION_LEDGER.md',
 'P_PREREG':'docs/thesis/PREREGISTRATION_20260912T053329Z.md',
 'P_LOEO':P+'/reports/loeo_summary.json',
 'P_LOEO_REPORT':'docs/thesis/FUSION_RESULTS_20260912T111025Z.md',
 'P_RAW':'docs/thesis/RAW_VIB_20260927T095726Z.md',
 'P_SECTOR':'docs/thesis/TOOTH_SECTOR_20260927T102354Z.md',
 'P_SCREEN':'data/rawvib/l1_screen.json',
 'P_SECTOR_SCREEN':'data/rawvib/sector_screen.json',
 'P_POS':'docs/thesis/CLOSING_TASK_C_SYNTHETIC.json',
 'P_CLOSE':'docs/thesis/CLOSING_EXPERIMENTS_20260912T171608Z.md',
 'P_INSPECT':'docs/thesis/INSPECTION_RESULT_20260913T204715Z.md',
 'P_DINO':'docs/thesis/ANOMALYDINO_RESULT_20260913T215556Z.md',
 'P_PROFILE':'docs/thesis/PROFILE_DIAGNOSTICS_V3.json',
 'P_FUSION':'docs/thesis/SQ2_SQ3_RESULTS.json',
 'P_RECOVERY':'docs/phm2026/RAW_DATA_RECOVERY.md',
 'P_RETIREMENT':'artifacts/phm2026/PHM_RAW_RETIREMENT_REPORT.md',
 'INTEL':'artifacts/intel_welding/audits/PHASE_1_GATE_REPORT.md',
 'R_FINAL':'artifacts/reassemble/reports/FINAL_REASSEMBLE_HANDOFF.md',
 'R_STORY':'artifacts/reassemble/reports/THESIS_STORYLINE_ADDENDUM.md',
 'R_MAP':'artifacts/reassemble/reports/FINAL_EVIDENCE_MAP.md',
 'R_CROSS':'artifacts/reassemble/reports/CROSS_STUDY_SYNTHESIS_HANDOFF.md',
 'R_S1':S1+'/assessment/results.json',
 'R_S1_REPORT':'artifacts/reassemble/reports/SECTION_1_UNIMODAL_HANDOFF.md',
 'R_S1B':S1B+'/assessment/results.json',
 'R_S1B_REPORT':'artifacts/reassemble/reports/SECTION_1B_FUSION_ADMISSIBILITY_HANDOFF.md',
 'R_S2':S2+'/assessment/results.json',
 'R_S2_REPORT':'artifacts/reassemble/reports/SECTION_2_FUSION_HANDOFF.md',
 'R_S3':S3+'/results.json',
 'R_S3_REPORT':'artifacts/reassemble/reports/SECTION_3_ROBUSTNESS_HANDOFF.md',
 'R_DROP':DROP+'/results.json',
 'R_DROP_REPORT':'artifacts/reassemble/reports/MODALITY_DROPOUT_HANDOFF.md',
 'R_AUDIO':AUDIO+'/results.json',
 'R_AUDIO_REPORT':'artifacts/reassemble/reports/AUDIO_FEASIBILITY_HANDOFF.md',
 'R_OBJECT':OBJ+'/results.json',
 'R_OBJECT_REPORT':'artifacts/reassemble/reports/OBJECT_GENERALIZATION_FEASIBILITY.md',
 'R_EFF':EFF+'/results.json',
 'R_EFF_REPORT':'artifacts/reassemble/reports/EFFICIENCY_HANDOFF.md',
 'R_FIGURES':FINAL+'/figure_index.json',
 'EX_VIS':EX+'/01_temporal_visual/comparison/results.json',
 'EX_SENSOR':EX+'/02_patchtst_training_budget/comparison/results.json',
 'EX_GATE':EX+'/03_static_anchored_adaptation/comparison/results.json',
}

def read(path): return json.loads(Path(path).read_text())
def sha(path):
 h=hashlib.sha256()
 with Path(path).open('rb') as f:
  for b in iter(lambda:f.read(1024*1024),b''): h.update(b)
 return h.hexdigest()
def paths(ids): return [SOURCES[x] for x in ids.split()]
def table(headers, rows):
 def cell(v):
  if isinstance(v,list): v='; '.join(str(x) for x in v)
  return str(v).replace('|','\\|').replace('\n','<br>')
 return '| '+' | '.join(headers)+' |\n| '+' | '.join(['---']*len(headers))+' |\n'+''.join('| '+' | '.join(cell(x) for x in r)+' |\n' for r in rows)+'\n'
def link(path,base='docs/thesis'):
 return f'[{path}]({os.path.relpath(path,base)})'
def source_links(ids): return '; '.join(link(p) for p in paths(ids))
def dump(obj): return json.dumps(obj,indent=2,ensure_ascii=False,allow_nan=False)+'\n'

COMPLIANCE=[]
def c(item,intention,form,dataset,method,evidence,status,reason,safe,limit,ids,chapter):
 COMPLIANCE.append(dict(zip(['original_item','original_wording_or_intention','final_implemented_form','dataset','experiment_or_method','main_evidence','status','reason_for_deviation','thesis_safe_interpretation','remaining_limitation','source_paths','suggested_chapter'],[item,intention,form,dataset,method,evidence,status,reason,safe,limit,paths(ids),chapter])))

c('MAIN RQ','Repository proxy: How can a process-aware multimodal AI architecture be designed and evaluated for robust industrial anomaly detection?','Two task-specific studies with signal, complementarity, feasibility and robustness gates','PHM + REASSEMBLE','LOEO regression; nested recording-disjoint failure classification','PHM sensor gain unresolved; REASSEMBLE static fusion adds information; original adaptive robustness not established','ADAPTED','Dataset and task changed as signal and protection gates were audited','Conditions for useful fusion are evaluated; architectural sophistication is not itself evidence of benefit','Original approved wording unavailable; neither study establishes general industrial deployment','RQ P_LOEO R_FINAL R_CROSS','Introduction / Research design / Discussion')
c('SQ1 visual representation','Repository proxy: lightweight or pretrained Transformer representations for visual data','Frozen RT-DETR backbone features and trained segment head; PHM privileged/offline image reference','REASSEMBLE; PHM secondary','16 hand-camera frames, spatial/temporal pooling; image-label qualification','Visual AP 0.2307 alone; complementary failure errors and incremental static fusion','PARTIALLY ANSWERED','Representation usefulness tested for segment outcomes rather than bounding boxes','The tested visual representation adds useful information to statistical sensors on this cohort','The core uses the convolutional RT-DETR ResNet backbone, not its Transformer encoder/decoder; standalone AUROC improvement over action context is unresolved','RQ R_S1 R_S1B P_INSPECT','Methods / Results SQ1')
c('SQ1 sensor time series','Repository proxy: Transformer suitability for sensor time series','PatchTST compared with engineered statistics; statistics selected for core fusion','REASSEMBLE; PHM','Frozen nested procedure; 512 positions, 22 channels; 220 statistics','AP statistics 0.4294 versus tested PatchTST 0.2416','ANSWERED','Model choice follows retained evidence instead of named-architecture preference','Tested PatchTST is an SQ1 negative result; statistics are the selected core representation','Bounded schedules, cohort and architecture; later longer-budget extension is separate','RQ R_S1 R_S1B P_LOEO','Methods / Results SQ1')
c('SQ1 audio representation','Repository proxy: suitability of audio Transformer representations','Feasibility audit only; AST and trimodal training excluded','REASSEMBLE','Independent annotation-to-waveform clock mapping required','No independently verified alignment mapping','NOT RUN — GATE FAILED','Nominal media coverage cannot substitute for clock validation','Audio performance remains unanswered','No audio representation comparison or audio corruption experiment','RQ R_AUDIO R_AUDIO_REPORT','Methods gates / Limitations')
c('SQ2 unimodal baselines','Repository proxy: compare unimodal and fusion models','Prior/action controls, visual, statistics and PatchTST baselines','REASSEMBLE; PHM separately','Nested grouped classification; LOEO regression','Current metric and paired-uncertainty tables retained','ANSWERED','Separate prediction targets require separate metric tables','Baseline strength and task definition determine the fusion comparison','No numerical pooling of regression and classification','RQ R_S1 P_LOEO','Results SQ2')
c('SQ2 concatenation','Repository proxy: simple concatenation fusion','F3 embedding concatenation and bounded MLP grid','REASSEMBLE','Two configurations; training-only selection and calibration; three seeds','AP 0.4122; versus statistics ΔAP −0.0172, interval crosses zero','ANSWERED','Frozen tested embeddings used; no architecture expansion','Concatenation did not demonstrate an improvement over statistics','Not evidence that all concatenation designs fail','RQ R_S2','Methods / Results SQ2')
c('SQ2 modular late fusion','Repository proxy: modular late fusion, including learned convex combination','Uniform F1 and three-parameter logistic probability stacker F2','REASSEMBLE','Strict inner OOF branch predictions; no fitting on outer-test OOF','F2 AP 0.4473 versus statistics 0.4294; paired ΔAP +0.0179 [0.0086,0.0283]','ADAPTED','Logistic probability stacking replaces the Intel contract’s convex weighting formulation','Minimal learned static fusion demonstrates incremental information on the frozen cohort','Adaptive same-cohort follow-up; not independent confirmation or a convex gate','RQ R_S1B R_S2','Methods / Results SQ2')
c('SQ2 process-aware gated fusion','Repository proxy: process-aware gated cross-modal fusion','F4 action, F5 quality, F6 action+quality masked scalar logit gates','REASSEMBLE','Two shared gate configurations; matched folds, three seeds and ablations','No original gate qualifies over F2; F6 ΔAUROC −0.0194 [−0.0288,−0.0102]','ADAPTED','Late allocation gates operationalize process awareness; no temporal cross-attention claim','Original gates did not establish incremental clean value over static fusion','Bounded designs; exploratory static-anchored adaptation is a distinct later study','RQ R_S2 R_S2_REPORT','Methods / Results SQ2 / Discussion')
c('SQ3 missing modalities','Repository proxy: robustness under missing modalities','Complete visual/sensor removal, exact branch fallback and abstention rules','REASSEMBLE','V4/S5; unavailable unimodal model abstains; fusion adopts surviving probability and threshold','All fusion arms collapse exactly to the available branch','ANSWERED','Two validated modalities permit two single-loss cases, not seven trimodal cases','Graceful fallback is guaranteed by implementation','Structural fallback does not show learned robustness or improved surviving-branch performance','RQ R_S3 R_DROP','Methods / Results SQ3')
c('SQ3 degraded modalities','Repository proxy: robustness under degraded/unreliable modalities','Clean-trained visual/sensor corruption suite; no corruption-driven tuning','REASSEMBLE','Six graded families plus missingness/stuck channels; paired recording bootstrap','Original gates do not establish a superior robustness mechanism','ANSWERED','Audio removed; operators act on supported visual/sensor inputs','Performance under declared synthetic corruptions is measured','One deterministic corruption realization per core condition; not production-fault coverage','RQ R_S3','Results SQ3 / Limitations')
c('SQ3 adaptive robustness','Repository proxy: can gating improve robustness?','Weight-direction and outcome criteria; matched modality-dropout follow-up','REASSEMBLE','12 family/gate high-severity checks; fixed dropout probabilities','0/12 original mechanism checks qualify; dropout outcomes mixed','ANSWERED','Test falsifiable criteria instead of treating moving weights as success','The completed core did not demonstrate the proposed adaptive robustness advantage','Does not prove no possible gate can work; ongoing repeated-corruption extension excluded','RQ R_S3 R_DROP','Results SQ3 / Discussion')
c('SQ4 predictive metrics','Repository proxy: evaluate beyond accuracy','Task-specific predictive tables and paired uncertainty','Both studies separately','PHM MAE/RMSE/rank; REASSEMBLE AUROC/AP and threshold metrics','Retained LOEO and recording-disjoint OOF outputs','ADAPTED','Image-derived regression target versus segment failure labels','Each study answers its own operational prediction question','Metric values are not comparable across task scales','RQ P_LOEO R_S2','Evaluation protocol / Results')
c('SQ4 calibration','Repository proxy: evaluate calibration','Training-only sigmoid calibration; Brier and 15-bin ECE','REASSEMBLE','Strict OOF calibration; F2 logistic likelihood on branch probabilities','F2 ΔBrier −0.00201 with negative CI; ΔECE interval crosses zero','ANSWERED','Quantitative calibration evidence replaces qualitative confidence claims','Brier improves; additional ECE improvement remains unresolved','Brier also reflects discrimination; binning and deployment prevalence matter','RQ R_S1B R_S2','Results SQ4')
c('SQ4 interpretability','Repository proxy: evaluate interpretability','Action/quality weight plots and controlled input ablations','REASSEMBLE','Gate-weight changes and corruption direction checked against outcomes','Weight variation does not establish useful reliability adaptation','PARTIALLY ANSWERED','Mechanistic diagnostics substitute for unsupported semantic interpretations','Measured allocation response is inspectable','No causal reliability understanding, expert validation or human interpretability study','RQ R_S2 R_S3','Results SQ4 / Discussion')
c('SQ4 modularity','Repository proxy: evaluate modularity','Explicit branch probability interfaces, masks and fallback','REASSEMBLE','Uniform, learned static and gated heads share frozen branches','Retained common inputs/checkpoints and exact missingness parity','PARTIALLY ANSWERED','Modularity operationalized as replaceable implementation interfaces','Components can be evaluated separately','Unseen branch substitution still requires calibration/refitting; no cost-free hot swap demonstration','RQ R_S2 R_S3 R_EFF_REPORT','Architecture / Discussion')
c('SQ4 latency and compute','Repository proxy: report compute, latency and usability','Parameter, checkpoint, memory and warm component timings','REASSEMBLE','T4, four CPU threads, three deterministic segments','U1 26.27 ms; F2 504.69 ms sequential component sum','PARTIALLY ANSWERED','A bounded benchmark replaces an unperformed deployment trial','Statistics are much cheaper in this measured setting','Cached compressed video, RAM sensors, three segments; no end-to-end production SLA','RQ R_EFF R_EFF_REPORT','Results SQ4 / Limitations')
c('SQ4 practical usability','Repository proxy: practical industrial usability','Task semantics, thresholds, fallback and cost trade-offs documented','Both studies','Evidence-qualified design discussion','No prospective plant or operator trial','PARTIALLY ANSWERED','Available offline data supports research evaluation only','Provides an auditable evaluation design and bounded findings','No user study, prospective safety/utility validation or production readiness claim','RQ P_TARGET R_FINAL R_EFF','Discussion / Limitations')
c('PHM dataset pivot','Intention inferred from retained study records: industrial multimodal anomaly research','Study 1 remains a target/signal and evaluation-conditions study; does not supply a positive deployable visual-sensor fusion claim','PHM','Image-derived damage regression and bounded sensor tests','LOEO gain unresolved; physical tooth identity/alignment and target uncertainty constrain fusion','ADAPTED','Data supports provisional regression more directly than validated online multimodal anomaly detection','Negative and feasibility findings remain part of the thesis','Exact original proposed dataset and approval history cannot be certified without exposé/master record','P_TARGET P_LOEO P_RAW P_CLOSE','Research design / Study 1')
c('Intel audit / no-go','Repository proxy: session-disjoint protected final evaluation','Audit retained; new model programme stopped at protection gate','Intel welding','Session and exposure audit','216 supplied-split session crossings; proposed holdout already exposed; zero new audit-phase models','NOT RUN — GATE FAILED','A protected final-test claim could not be sustained','Dataset rejection is a protocol decision','No evidence that Intel encoders perform poorly; intended-condition labels are not physical defect truth','RQ INTEL','Dataset selection / Limitations')
c('REASSEMBLE introduction','Intention inferred: an admissible multimodal industrial task','Study 2: annotated pick/insert/remove/place segment failure classification','REASSEMBLE','148 recordings, 4530 primary dual-complete segments, 509 failures','Recording-disjoint nested evidence supports static visual-sensor fusion','ADAPTED','Provides aligned visual/sensor observations and explicit segment outcomes','A complementary task evaluates fusion under different evidence conditions','Same physical objects/environment may recur; not independent physical-object OOD','R_FINAL R_MAP R_S1B','Research design / Dataset')
c('RT-DETR: representation, not detection','Named visual architecture in repository task lineage; approved detector wording unverified','Frozen RT-DETR ResNet backbone spatial features with segment-level classification head; Transformer encoder/decoder unused in the core','REASSEMBLE','16-frame temporal mean in completed core','Segment AP/AUROC, not bounding-box AP','ADAPTED','No detector fine-tuning or detection target in completed core','A pretrained detector backbone is used as a visual representation','Do not describe task metrics as object-detection performance or evidence that the detector’s Transformer layers were evaluated','R_S1_REPORT R_S1','Methods SQ1')
c('PatchTST not selected','Named temporal Transformer suitability is a testable question','Retained as bounded SQ1 negative; not the core fusion branch','REASSEMBLE','3/6-epoch candidate schedules; statistics control','AP 0.2416 versus 0.4294 statistics','ADAPTED','Selection follows paired predictive evidence','Testing a proposed model does not require it to win','Later 24/48-epoch exploratory result must remain separate from historical Section 1','R_S1 EX_SENSOR','Results SQ1 / Exploratory appendix')
c('Statistics selected','Intention inferred: choose a defensible sensor representation','220 statistics, training-only scaling, regularized logistic model','REASSEMBLE','C in {0.1,1,10}; nested selection and calibration; conditional permutation','Strongest core sensor arm; observed AP 0.4294 above all 19 structured null draws','ADAPTED','Simpler model outperformed tested temporal Transformer','Engineering baselines are scientifically consequential','Conditional null preserves recording/action structure and has coarse p resolution','R_S1 R_S1B','Methods / Results SQ1')
c('Audio alignment exclusion','Audio branch intended in repository proxy','No AST, trimodal or audio-corruption training','REASSEMBLE','Alignment feasibility gate','No independently verified clock mapping','NOT RUN — GATE FAILED','Cannot justify waveform-to-segment labels','Audio SQ1/SQ3 components remain untested','Nominal coverage is not evidence of valid synchronization','R_AUDIO_REPORT R_AUDIO','Methods gates / Limitations')
c('Physical-object OOD exclusion','Extension intention: generalize to unseen physical objects','Feasibility audit only','REASSEMBLE','Physical-instance identity and recording/category graph audit','17 categories; one connected component spans 148 recordings; instance IDs unverified','NOT RUN — GATE FAILED','Category labels are not physical-instance identities; valid split not established','No object-OOD result is claimed','Recording-disjoint evaluation is narrower than object-disjoint generalization','R_OBJECT_REPORT R_OBJECT','Methods gates / Limitations')
c('Regression versus classification','Repository proxy targets anomaly detection; PHM operational target changed','PHM continuous provisional damage score; REASSEMBLE binary annotated failure','Both studies','Separate result tables and uncertainty units','20 PHM run units versus 148 REASSEMBLE recording clusters','ADAPTED','Target semantics and labels differ','Research design connects the studies; metric magnitudes do not','Neither task establishes all industrial anomaly types','P_TARGET P_LOEO R_CROSS','Research design / Evaluation')
c('Old Section 1 standalone fusion gate','Both branches required simultaneous standalone improvement before fusion','Section 1B explicitly evaluates incremental information beyond the strongest branch','REASSEMBLE','Strict nested logistic stacking plus complementary errors and structured sensor null','Original Section 1 CONDITIONAL retained; Section 1B GO is a different question','SUPERSEDED','A weaker standalone model may still add useful information','Incremental gain supports fusion without rewriting the standalone finding','Outcome-informed follow-up; not independent confirmation','R_S1_REPORT R_S1B_REPORT','Evaluation evolution / Discussion')
c('Exploratory extension boundary','User-authorized separate bounded additional-improvements study','Completed temporal, budget and static-anchored comparisons segregated; pending refinements excluded','REASSEMBLE','Same cohort/folds; dedicated timestamped extension run','Some positive and negative exploratory results retained; extension not complete at freeze','PARTIALLY ANSWERED','Post-core questions require their own outcome-informed status','Original conclusions remain historical; new evidence is labelled by scope','No overall extension completion or automatic combination of winning changes','EX_VIS EX_SENSOR EX_GATE R_STORY','Exploratory appendix / Limitations')

CLAIMS=[]
P_PROTOCOL='PHM-P: 3 experiment-disjoint outer folds, 20 run units, training/validation experiment rule fixed; run-cluster paired bootstrap 10000. Historically exposed study; no fresh final holdout.'
R_PROTOCOL='REAS-R: frozen 5 outer / 4 inner recording-disjoint folds; 4530 segments / 509 failures / 148 recordings; training-only selection/calibration/thresholds; paired recording bootstrap 2000. Same-cohort adaptive research.'
def cl(cid,sentence,study,rq,evidence,point,uncertainty,protocol,ids,status,limitation,overstatement,placement='Main text',era='current'):
 CLAIMS.append(dict(zip(['claim_id','exact_proposed_thesis_sentence','study','rq_sq','evidence','point_estimate','uncertainty','evaluation_protocol','artifact_paths','evidence_status','important_limitation','allowed_wording','overstatement_to_avoid','placement','era'],[cid,sentence,study,rq,evidence,point,uncertainty,protocol,paths(ids),status,limitation,sentence,overstatement,placement,era])))
cl('P01','Under the retained PHM leave-one-experiment-out protocol, neither tested sensor model demonstrated lower MAE than the training-mean constant baseline.','PHM','MAIN / SQ1 / SQ2','Retained out-of-experiment predictions and paired differences','MAE: constant 0.804156; three sensor-submodality encoders 0.823786; single PatchTST 0.941455 percentage points','Bootstrap-mean ΔMAE: fused +0.017668 [−0.196189,0.227769]; PatchTST +0.135838 [−0.085423,0.355913] (95%)',P_PROTOCOL,'P_LOEO P_LOEO_REPORT','Supported bounded negative','Direct empirical differences are +0.019629 and +0.137299; stored paired point estimates are bootstrap means. Fused arm is sensor-submodality fusion, not visual+sensor.','The constant is universally best; the data contains no signal.')
cl('P02','The current PHM target is a provisional image-derived damage score, rather than independently validated physical damage ground truth.','PHM','MAIN / SQ4','Current target ledger, segmentation quality and repeated-photo diagnostics','v3: teeth 5–28; deterministic image per tooth; mean worst 3 scores; 480 tooth-run rows / 20 runs','Repeated-photo within-tooth SD about 0.796 percentage points is descriptive, not a model-error floor','Target definition and image diagnostics; no population error bound','P_TARGET P_PROFILE','Supported target limitation','Different aggregation levels and lighting/segmentation uncertainty; v1/v2/median variants cannot be mixed.','The target is exact damage; every MAE below 0.796 is impossible.','Methods / Limitations')
cl('P03','Blind inspection of selected image-score extremes provided limited visual support for the PHM target ordering.','PHM','SQ1 / SQ4','Retained inspection report and validated DINO comparison CSV','30/38 unambiguous labels agree (78.9%); 42 selected, 4 unsure; rank correlation 0.6007','Wilson 95% interval approximately [0.637,0.889]; indicative pooled binomial p=0.0005','One observer; 7 high and 7 low images per experiment; extreme-selected sample','P_INSPECT P_DINO','Supported with selection limits','Not random population validation; low/high middle gap unsampled; per-experiment p values A .1796/B .0654/F .0225.','All experiments independently validate the continuous ground truth.','Results / Limitations')
cl('P04','Raw vibration checks recovered expected shaft and mesh frequencies and closely matched organizer TSA waveforms after circular alignment.','PHM','SQ1 / reproducibility','Raw and sector diagnostic reports; retained features and TSA arrays','102.4 kHz; shaft 23.333 Hz; mesh about 653.32 Hz; median best-circular TSA correlation .997; all 472 above .9','Descriptive checks; no inferential population interval reported','577 queued / 551 readable / 25 too few revolutions / 1 unreadable; 472 steady files, 20 runs','P_RAW P_SECTOR','Supported preprocessing validation','Circular alignment does not register an absolute physical tooth; startup ramp excluded.','Validated acquisition proves predictive damage information or physical-tooth correspondence.')
cl('P05','The bounded PHM sensor screens did not demonstrate the required EXP-F target association, so dependent modeling stages were not run.','PHM','SQ1 / MAIN','DAQ, physics and tooth-sector screens','EXP-F: 7/72, 16/50 and 26/80 features meet |rho|≥.5; sector correct-sign survivors 0','300 within-experiment run-label permutations: p=.866667, .223333, .223333 respectively','Run-mean features; predeclared gate; seed 20260912','P_SCREEN P_SECTOR_SCREEN P_RAW P_SECTOR','Supported bounded negative','Finite features, aggregation and sampled times; EXP-B empirical p=0 in 300 draws means zero exceedances, not zero probability.','Sensors cannot detect damage; all temporal architectures must fail.')
cl('P06','A synthetic target-aligned positive control showed that the tested PHM pipeline could learn the deliberately injected signal.','PHM','SQ1 / methodological control','Retained per-seed aggregate synthetic experiment','Alpha .2 mean MAE .161575 versus constant .804156; 3/3 model seeds improve','Seed paired ΔMAE CIs: [−.807379,−.421799], [−.860515,−.468705], [−.864624,−.433357]','Same LOEO scheme; model seeds 1/2/3; 10000 bootstrap; seed 20260912','P_POS P_CLOSE','Supported positive control','Artificial label-aligned channels; aggregates retained but per-run predictions/checkpoints not identified. Does not rule out every bug or establish absence of natural signal.','The control proves real PHM sensors contain no information.')
cl('P07','The PHM image reference provides qualified evidence of image-score association but is not an experiment-disjoint multimodal deployment result.','PHM','SQ1 / SQ2','Historical R4 image row explicitly excluded from LOEO','R4: rho .659341 on 13 A/F runs; MAE 1.826411 against v3; no B predictions','No comparable LOEO paired effect asserted for this row',P_PROTOCOL+' Image reference separately labelled.','P_LOEO P_CLOSE P_TARGET','Historical qualified evidence','Model trained under older target/history; EXP-B training, no B predictions; physical-tooth sensor linkage unavailable.','RT-DETR achieved rho .659 on independent LOEO physical damage.','Appendix / Discussion','historical')
cl('P08','Repeated inspection of historical EXP-F results prevents treating that split as an untouched final test set.','PHM','Evaluation validity','Preregistration and target/version history','No new numerical effect claimed','Not applicable; protocol limitation','Historical exposure remains relevant even after LOEO','P_PREREG P_TARGET P_LOEO_REPORT','Documented limitation','LOEO controls within-fit group leakage but cannot undo adaptive study selection.','The historical EXP-F result is a one-time confirmatory test.','Methods / Limitations')
cl('P09','PHM regression error and REASSEMBLE classification discrimination answer different target questions and are reported on separate scales.','Both','SQ4','Task definitions and retained metric sources','PHM MAE/RMSE in score percentage points and Spearman; REASSEMBLE AUROC/AP plus threshold and calibration metrics','Study-specific run/recording clustering; no pooled cross-task effect','PHM-P and REAS-R','P_TARGET P_LOEO R_S2 R_CROSS','Supported reporting rule','Neither scale is a cross-dataset ranking of industrial usefulness.','AUPRC .447 is better or worse than MAE .804.','Methods / Discussion')
cl('P10','On the selected inspection subset, the explored AnomalyDINO settings did not demonstrate an improvement over the retained image heuristic.','PHM','SQ1 / target validation','Validated sweep report and CSV','Best explored 29/38; heuristic 30/38; prespecified DINO 23/38','Wilson intervals best [.608,.870], heuristic [.637,.889], prespecified [.447,.744]; best-vs-heuristic McNemar p=1.0','20 explored configurations on the selected inspection sample','P_DINO P_INSPECT','Supported bounded negative','Outcome-informed best setting and small selected sample; not an equivalence test.','DINO is equivalent or universally inferior to the heuristic.','Appendix / Discussion')
cl('P11','PHM sensor-submodality fusion and corruption tests did not establish a practically useful multimodal robustness advantage on the provisional target.','PHM','SQ2 / SQ3','Retained SQ2/SQ3 result JSON','MAE constant .8042; modular A3 .8288; gated A4 .9074; concat A2 .9643','A3−A4 ΔMAE about −.0781 [−.1619,−.0046]','PHM experiment-disjoint protocol; sensor-submodality partitions only','P_FUSION P_LOEO','Supported bounded negative','Flat corruption curves from weak models are not robustness; empty encoder dropout is vacuous.','Flat degradation proves robust cross-modal adaptation.','Appendix / Discussion')
cl('I01','The Intel welding modelling programme was stopped because the required protected evaluation boundary could not be established from the audited state.','Intel audit','MAIN / evaluation validity','Phase 1 leakage and exposure audit','4040 rows / 236 sessions; 216 supplied-split crossings; proposed 32-session holdout exposed; zero new audit-phase models','Not a model performance estimate','Read-only session-based audit','INTEL RQ','NOT RUN — GATE FAILED','Intended welding conditions are not expert physical defect truth; no replacement split searched until something passes.','Intel representations performed poorly.','Dataset selection / Limitations')
cl('R01','Engineered sensor statistics outperformed the tested PatchTST representation on the frozen REASSEMBLE core evaluation.','REASSEMBLE','SQ1','Retained OOF predictions and paired assessment','AP .429392 versus .241591; statistics AUROC .779325','Statistics−PatchTST paired ΔAP +.187801 [.140711,.231443]; ΔAUROC +.073973 [.046921,.100353] (95%)','REAS-R; core PatchTST 3/6-epoch grid','R_S1 R_S1_REPORT','Supported core comparison','Limited architecture and budget; selection applies to the frozen core, not every possible temporal model.','Transformers are unsuitable for industrial sensors.')
cl('R02','The statistical-sensor result exceeded all 19 conditional permutation controls preserving recording/action label structure.','REASSEMBLE','SQ1 / control','Full frozen nested procedure rerun under circular shifts','Observed AUROC .779325; AP .429392; null AUROC .601356–.669258, AP .150210–.191530','Plus-one p=.05 for AUROC and AP; minimum attainable p with 19 draws','REAS-R; chronological circular shifts separately within recording/action strata','R_S1B','Supported conditional control','Specific conditional null; not IID-label chance, broad causal identification or high-resolution significance.','All recording/action confounding has been eliminated.')
cl('R03','The core RT-DETR representation showed evidence beyond action context in AP, while its standalone AUROC improvement remained unresolved.','REASSEMBLE','SQ1','Section 1 action-control contrasts','RT-DETR AP .230658; AUROC .697795','Versus action-only: paired ΔAP +.049853 [.022512,.083634]; ΔAUROC +.012705 [−.015442,.040630] (95%)','REAS-R; frozen pretrained backbone and bounded trained head','R_S1 R_S1_REPORT','Supported qualified finding','Standalone gate remained CONDITIONAL; this is segment classification using the ResNet backbone, not object detection or a test of RT-DETR Transformer layers.','The standalone visual branch passed every original signal gate.')
cl('R04','The core visual and statistical-sensor branches made complementary OOF errors, including 97 failures detected only by the visual branch.','REASSEMBLE','SQ2 / complementarity','Correctness overlap at training-selected thresholds','All: both correct 2347, both wrong 529, visual-only 486, sensor-only 1168; score correlation .3130; error correlation .1627','Failure rescue fraction .19057, recording-cluster 95% [.15419,.22847]; 97 rescues in 61 recordings','REAS-R; descriptive oracle and action-specific overlap retained','R_S1B','Supported complementarity','Failure overlap: both correct 240, both wrong 99, visual-only 97, sensor-only 73; oracle 410/509 is not deployable.','A deployable oracle achieves the overlap accuracy or every action benefits equally.')
cl('R05','Strictly nested learned static late fusion improved AP and AUROC beyond the statistical-sensor branch on the frozen REASSEMBLE cohort.','REASSEMBLE','MAIN / SQ2','Section 1B F2, reused exactly in Section 2','AP .447299 versus .429392; AUROC .794968 versus .779325','Paired ΔAP +.017907 [.008603,.028284]; ΔAUROC +.015644 [.006030,.025465]','REAS-R; deeper branch cross-fitting inside outer training; logistic stacker never fit on outer-test OOF','R_S1B R_S2','Supported incremental value','Same-cohort outcome-informed follow-up, not independent confirmatory evidence; modest absolute gain.','Fusion is universally superior or independently confirmed.')
cl('R06','The tested concatenation model did not demonstrate an AP improvement over the statistical-sensor baseline.','REASSEMBLE','SQ2','F3 versus U1 matched comparison','F3 AP .412231; ΔAP −.017160','Paired 95% [−.057276,.022977]','REAS-R; two fixed MLP candidates; three seeds','R_S2','Supported unresolved gain','An interval crossing zero does not establish equivalence or definite inferiority.','Concatenation has been proved worse in all settings.')
cl('R07','None of the original process/quality gates established clean incremental value over static F2, and the combined F6 gate had lower AUROC.','REASSEMBLE','SQ2','F4–F6 qualification and paired tables','F6 AP .441356; ΔAP −.005943; ΔAUROC −.019445','ΔAP 95% [−.024796,.013695]; ΔAUROC [−.028801,−.010239]; simultaneous AP criterion fails','REAS-R; three adaptive-vs-F2 claims use additional Bonferroni lower bounds','R_S2','Supported core finding','Original logit-gate family only; later static-anchored adaptive model is separate exploratory evidence.','No adaptive architecture can ever improve on static fusion.')
cl('R08','Under the declared core corruption suite, the original gates did not jointly establish the expected weight response and improved performance retention over F2.','REASSEMBLE','SQ3','Frozen clean-trained models, mechanism and outcome checks','0/12 graded family/gate high-severity checks qualify','Paired recording-cluster intervals, conditional on fitted models and one fixed corruption realization per condition','REAS-R; six graded families, F5/F6; no test-time tuning','R_S3 R_S3_REPORT','Supported bounded negative','Synthetic faults and marginal family-specific uncertainty; repeated-realization extension not included.','The gates are universally nonrobust or all real faults were covered.')
cl('R09','Changing gate weights did not by itself demonstrate learned modality reliability.','REASSEMBLE','SQ3 / SQ4','Action/quality ablations and corruption mechanism audit','High visual-noise F6 degraded-visual weight shift +.22458','Paired 95% [.16042,.28970], opposite the expected down-weighting direction','REAS-R; gate response coupled to outcome criteria','R_S2 R_S3','Supported interpretation constraint','Some sensor conditions down-weight the damaged branch without establishing a predictive advantage.','The gate understood which modality was trustworthy.','Results / Discussion')
cl('R10','Exact remaining-branch fallback under complete modality loss was structural and therefore was not evidence of a learned robustness gain.','REASSEMBLE','SQ3 / modularity','V4/S5 probability and threshold parity','All fusion predictions equal the available calibrated branch; unavailable unimodal arm abstains','Deterministic identity check; no effect estimate is needed','REAS-R; explicitly implemented missingness convention','R_S3 R_DROP','Supported structural result','Remaining branch can still be wrong; both-missing deployment is not validated.','Modality dropout learned a superior complete-loss fallback.')
cl('R11','Modality-dropout training produced mixed condition-specific changes and did not establish an overall robustness improvement.','REASSEMBLE','SQ3','Matched F6 dropout and clean-trained F6','Clean AP .437651; ΔAP −.003705; S2_.3 positive and V1_.05 negative condition-specific changes','Clean ΔAP 95% [−.008546,.000288]; all condition intervals retained','REAS-R; .15 visual-missing / .15 sensor-missing / .70 both-present; three seeds; 75 fits','R_DROP R_DROP_REPORT','Supported mixed result','Exact complete-loss fallback remains unchanged; no blanket benefit inferred from selected conditions.','Dropout conclusively harms clean AP or generally solves missing modalities.')
cl('R12','Audio modelling was excluded because an independent annotation-to-waveform alignment could not be verified.','REASSEMBLE','SQ1 / SQ3','Audio feasibility audit','Zero independently verified alignment mappings','Not a performance interval','Coverage is separate from clock-origin/drift verification','R_AUDIO R_AUDIO_REPORT','NOT RUN — GATE FAILED','AST, trimodal fusion and audio corruptions were not run.','Audio has no signal or AST performed poorly.','Methods / Limitations')
cl('R13','Physical-object OOD evaluation was not run because physical-instance identity and an admissible split were not established.','REASSEMBLE','Generalization','Object feasibility graph and identity audit','17 categories; one connected recording/category component spanning 148 recordings','Not a predictive uncertainty estimate','Feasibility audit; category names are not physical-instance IDs','R_OBJECT R_OBJECT_REPORT','NOT RUN — GATE FAILED','Recording-disjoint results do not establish novel-object generalization.','The models failed on unseen objects.','Methods / Limitations')
cl('R14','F2 improved Brier score over statistical sensors, while the additional ECE improvement remained unresolved.','REASSEMBLE','SQ4','Matched calibrated OOF predictions','Brier .078443 versus .080448; ECE .013812 versus .017396','ΔBrier −.002005 [−.003099,−.000908]; ΔECE −.003584 [−.012700,.009897]','REAS-R; sigmoid calibration on inner OOF; 15 equal-width ECE bins','R_S1B R_S2','Supported mixed calibration evidence','Brier includes discrimination; ECE uncertainty depends on binning and the small failure fraction.','F2 is perfectly calibrated or every calibration metric improves.')
cl('R15','In a bounded warm-component benchmark, statistical sensors were substantially cheaper than the visual-sensor pipeline.','REASSEMBLE','SQ4','Retained component measurements and checkpoint accounting','U1 26.267 ms; U2 478.415 ms; F2 504.693 ms; F6 564.021 ms; F2 3 fusion parameters, 11305285 total parameters','Timing repetitions retained; no population latency CI asserted','T4; four CPU threads; three deterministic segments; sensors in RAM, compressed-video cache; sequential component sums','R_EFF R_EFF_REPORT','Supported bounded efficiency measurement','Includes 11190112 frozen backbone parameters; not full production throughput or cold-start/network I/O; no prospective SLA.','The whole fusion system has only three parameters or is proven real-time.')
cl('R16','The common branch interfaces support modular evaluation, but replacing a branch still requires validating calibration and fusion behavior.','REASSEMBLE','SQ4','Shared predictions, masks, heads and retained nested inputs','Exact reuse of core F2 and branch probabilities','Structural implementation evidence, not a human-usability effect','REAS-R; component interface and missingness audits','R_S2 R_S3 R_EFF_REPORT','Supported architecture property','No unseen-encoder hot-swap or operator study was performed.','Any encoder can be replaced without retraining or evaluation.','Methods / Discussion')
cl('R17','REASSEMBLE results measure annotated segment failure classification with AP and AUROC, complemented by threshold and calibration metrics.','REASSEMBLE','MAIN / SQ4','Frozen label/cohort definition and metric tables','4530 segments; 509 failures (11.24%); 148 recordings; four actions','Recording-cluster intervals; threshold selection confined to training','REAS-R; AP is average precision, not trapezoidal PR area; balanced accuracy, macro-F1, failure recall/precision, Brier, ECE','R_S1 R_S2 R_FINAL','Supported task definition','Annotated failure is not general open-set anomaly discovery; no pointwise fault localization.','The reported AP is object-detection AP or general anomaly coverage.','Methods')
cl('E01','A separate exploratory temporal-visual comparison improved AP over both its mean-pooled and no-position controls.','REASSEMBLE extension','SQ1','Completed bounded temporal visual comparison only','V-TEMP .575180; V-MEAN .243399; V-NOPOS .489135','ΔTEMP−MEAN +.331781 [.287090,.372093]; ΔTEMP−NOPOS +.086045 [.055183,.115687]','Same frozen five folds, three seeds; nested training; 2000 paired recording bootstrap','EX_VIS','Completed exploratory comparison','Outcome-informed extension; mean control differs from original Section 1 head; fine-tuning refinement not included at this freeze.','An independently confirmed replacement for the complete thesis pipeline.','Exploratory appendix','exploratory')
cl('E02','A separate exploratory longer-budget PatchTST comparison improved over its short-budget control but remained below engineered statistics.','REASSEMBLE extension','SQ1','Completed bounded training-budget comparison','S-LONG AP .285311; S-6 .255658; statistics .429392','LONG−S6 +.029652 [.012193,.045106]; LONG−stats −.144081 [−.186123,−.100893]','Same frozen folds, three seeds; nested training; 2000 paired recording bootstrap','EX_SENSOR','Completed exploratory comparison','This does not rewrite the core 3/6-epoch negative result; hybrid refinement not finalized at freeze.','More epochs made PatchTST the selected sensor branch.','Exploratory appendix','exploratory')
cl('E03','A separate exploratory static-anchored adaptive fusion model improved AP over both matched static controls, with threshold and calibration trade-offs.','REASSEMBLE extension','SQ2','Completed static-anchored adaptation comparison','Adaptive AP .468312; A0 .447299; constant-residual .445680','Adaptive−A0 +.021014 [.001463,.041888]; adaptive−constant +.022633 [.003617,.043160]','Same cohort/folds; three seeds; nested training; 2000 paired recording bootstrap','EX_GATE','Completed exploratory comparison','Adaptive failure recall .587426 versus A0 .607073 and ECE .017964 versus .013812; point trade-offs, not claimed significant differences. Original gates remain a separate bounded negative; no robustness result implied.','All adaptive gating was unsuccessful, or clean gain proves robust adaptation.','Exploratory appendix','exploratory')
cl('X01','Historical PHM numbers from other target versions, exposed fixed splits or unretained code must not replace the current v3 LOEO results.','PHM','Evidence governance','Target ledger and historical provenance audit','Do not recycle 1.011, .6797/.680, .6557/.632/.7426, .8314, 1.020 or ambiguous .733 as current headline values','Not applicable; incompatible or unrecoverable provenance','Current v3 LOEO is separately identified','P_TARGET P_LOEO','Retired as current headline claims','Some values remain legitimate historical rows only with their exact target, split and aggregation labels.','An old attractive number is the final thesis result.','Retired-claims register','retired')
cl('X02','Neither absence of demonstrated gain nor a failed feasibility gate establishes absence of information in a modality.','Both','Interpretation guardrail','Bounded negatives, positive control and feasibility exclusions','No new point estimate','Unresolved intervals remain unresolved','Task- and gate-specific interpretation','P_LOEO P_POS R_AUDIO R_OBJECT INTEL','Retired overstatements','This sentence is a guardrail, not a new empirical claim.','PHM sensors contain no signal; audio is useless; Intel models failed; OOD performance is poor.','Limitations / Retired-claims register','retired')

REPRO=[]
RETAINED='REPRODUCIBLE FROM RETAINED ARTIFACTS'
RAW='REQUIRES RAW DATA RE-DOWNLOAD'
RETRAIN='REQUIRES MODEL RETRAINING'
DOC='DOCUMENTATION ONLY'
MISSING='BLOCKED / MISSING'
def rr(claim,run,configs,predictions,metrics,displays,scripts,commit,status,limit):
 REPRO.append(dict(zip(['claim','run','configs','predictions_or_observations','metric_sources','figures_or_tables','scripts','commit_identity','status','limitation'],[claim,run,configs,predictions,metrics,displays,scripts,commit,status,limit])))
rr('P01/P07: PHM LOEO and separately labelled image reference',P,[P+'/config/resolved_config.yaml'],[P+'/tables/loeo_predictions.parquet'],[SOURCES['P_LOEO']],[P+'/tables/loeo_summary.csv'],['scripts/phm2026/results/loeo_evaluation.py'],'c699cbd9727ed33f34f1785172db163eb74b071f (run provenance)',RETAINED,'Recompute reported metrics from retained predictions. No LOEO trained-state files identified. Snapshot retains a stale v2 target string and fixed split; source target artifact is v3 and evaluator/report explicitly override to LOEO. Preserve these historical metadata defects.')
rr('P02: PHM v3 target identity',T,[T+'/config/resolved_config.yaml',T+'/config/target_definition.yaml'],[T+'/tables/per_tooth_damage.parquet',T+'/tables/run_damage_targets.parquet'],[T+'/reports/target_quality_report.json',SOURCES['P_TARGET']],[T+'/figures/per_tooth_damage_heatmap.svg',T+'/figures/target_definition_pipeline.svg'],['scripts/phm2026/targets/derive_image_targets.py'],'246024367e8b8a0b2463274115d760fb579ef50c (run provenance)',RETAINED,'Retained target/quality tables can be inspected; rederivation from original archives requires recovery. Image heuristic is provisional, not verified damage truth.')
rr('P03/P10: selected-image validation','docs/thesis',[SOURCES['P_INSPECT'],SOURCES['P_DINO']],['docs/thesis/ANOMALYDINO_VALIDATED.csv','docs/thesis/ANOMALYDINO_SCORES.csv'],[SOURCES['P_INSPECT'],SOURCES['P_DINO']],['docs/thesis/ANOMALYDINO_SWEEP.csv'],['scripts/phm2026/results/anomalydino_validated.py','scripts/phm2026/results/anomalydino_sweep.py'],'183a8d29cd5a43705c77ac876b6ae31404955406 (inspection evidence commit)',RETAINED,'Selected sample/one observer; human judgement cannot be algorithmically recreated. Retained labels/scores support numerical inspection only.')
rr('P04/P05: raw/TSA and bounded signal diagnostics','data/rawvib',['scripts/rawvib/l1_screen.py','scripts/rawvib/sector_screen.py'],['data/rawvib/file_features.parquet','data/rawvib/sector_file_features.parquet','data/rawvib/tsa_index.parquet','data/rawvib/tsa_arrays.npz'],[SOURCES['P_SCREEN'],SOURCES['P_SECTOR_SCREEN'],SOURCES['P_RAW'],SOURCES['P_SECTOR']],[SOURCES['P_RAW'],SOURCES['P_SECTOR']],['scripts/rawvib/angular_features.py','scripts/rawvib/save_tsa.py','scripts/rawvib/sector_features.py','scripts/rawvib/l1_screen.py','scripts/rawvib/sector_screen.py'],'1a4a03a27b2c55a70c014c891c11f6559c0938a7 (retained report commit)',RETAINED,'Feature-level screens can be audited from retained data. Original TSA correspondence aggregate is reported; full raw-to-organizer waveform recomputation requires retired archives. No standalone config snapshot for these scripts; use defaults/commands recorded in the reports at the identified revision.')
rr('PHM raw-to-feature reconstruction','gtc-data-experiment',['configs/phm2026/download_manifest.json','configs/datasets/phm2026.yaml'],['artifacts/phm2026/raw_data_manifest.json'],[SOURCES['P_RECOVERY'],SOURCES['P_RETIREMENT']],[SOURCES['P_RECOVERY']],['src/phm2026/acquisition/phm_download.py'],'d634251 recovery implementation; 78394d7f9349f5f6858dabe1f3a796a48911bb57 pre-retirement',RAW,'Original archives were previously retired with approval. No download performed here; historical remote verification is not a guarantee of present availability.')
rr('P06: synthetic positive-control independent numerical rerun','docs/thesis',['scripts/phm2026/results/closing_task_c.py'],[],[SOURCES['P_POS'],SOURCES['P_CLOSE']],[SOURCES['P_CLOSE']],['scripts/phm2026/results/closing_task_c.py'],'9a79c613f2a10e85d077bc4d0c1e30c7cba93c88 (aggregate evidence commit)',RETRAIN,'Per-seed aggregate metrics and code retained; per-run predictions and checkpoints not identified. Existing result is documented, not independently regenerated.')
rr('P11: PHM sensor-submodality fusion numerical rerun','docs/thesis',['scripts/phm2026/results/sq2_sq3_fusion.py'],[],[SOURCES['P_FUSION']],[SOURCES['P_FUSION']],['scripts/phm2026/results/sq2_sq3_fusion.py'],'45eeed0f35c9c043697220d344dcead586ea9919 (aggregate evidence commit)',RETRAIN,'Aggregate metrics/code retained; per-run fitted-model predictions not identified. Do not reconstruct absent artifacts silently.')
rr('R01/R03: core unimodal comparison',S1,[S1+'/config.json'],[S1+'/predictions/'+m+'_perm00.npz' for m in ['sensor_statistics','patchtst','rtdetr']],[SOURCES['R_S1']],[FINAL+'/figures/03_unimodal.pdf',FINAL+'/tables/01_master_clean_metrics.csv'],['scripts/reassemble/05_section1_report.py','scripts/reassemble/20_completion_synthesis.py'],'852a12376b24f6b2d5084a625331c499808c38f4 training; 08d498d evidence',RETAINED,'Manifest verifies fitted artifacts; numerical checks use retained predictions. No independent training reproduction claimed.')
rr('R02/R04/R05: sensor control, complementarity and incremental fusion',S1B,[S1B+'/config.json'],[S1B+'/stacking/oof.npz'],[SOURCES['R_S1B']],[FINAL+'/figures/04_complementarity.pdf',FINAL+'/tables/12_clean_paired.csv'],['scripts/reassemble/07_section1b.py','scripts/reassemble/20_completion_synthesis.py'],'06f93d1309fac1117a6014f4145bf4cedb8b4985 implementation; 4089b02 evidence',RETAINED,'19 structured-null prediction sets and all nested fits retained via output_manifest.json; outer stacker train/test rows checked. Four of five fold AP effects positive; all leave-one-fold-out AP effects positive.')
rr('R05–R07/R14: clean fusion and calibration',S2,[S2+'/config.json'],[S2+'/predictions/oof.npz'],[SOURCES['R_S2']],[FINAL+'/figures/05_clean_fusion.pdf',FINAL+'/tables/01_master_clean_metrics.csv',FINAL+'/tables/12_clean_paired.csv'],['scripts/reassemble/09_section2.py','scripts/reassemble/20_completion_synthesis.py'],'e65d1dac83111ae167a23cd05a889a0fa74fd8f0 implementation',RETAINED,'inputs/ retains strict nested branch predictions; fits/ retains per-seed checkpoints; source identities in implementation.json. No fresh final-test claim.')
rr('R08–R10: original corruption and missingness',S3,[S3+'/config.json','configs/reassemble/section3_corruptions.json'],[S3+'/predictions/'+n+'.npz' for n in ['clean','V4','S5']],[SOURCES['R_S3']],[FINAL+'/figures/07_visual_corruptions.pdf',FINAL+'/figures/08_sensor_corruptions.pdf',FINAL+'/figures/09_missing_modalities.pdf',FINAL+'/figures/10_gate_response.pdf',FINAL+'/tables/03_robustness_paired.csv'],['scripts/reassemble/16_section3_report.py','scripts/reassemble/20_completion_synthesis.py'],'dd56773d0fb7e5df986301eaf873e03bd1124d31 seal; e952269bb34f29a239b0d6a267e1a53adc18acf7 final evidence',RETAINED,'All 22 condition prediction paths, source/feature hashes and model artifacts retained in run manifest. Conditional on one fixed realization per condition.')
rr('R10/R11: modality dropout',DROP,[DROP+'/config.json','configs/reassemble/section3_corruptions.json'],[DROP+'/predictions/clean.npz'],[SOURCES['R_DROP']],[FINAL+'/figures/11_dropout_tradeoff.pdf',FINAL+'/tables/07_modality_dropout.csv'],['scripts/reassemble/17_modality_dropout.py','scripts/reassemble/20_completion_synthesis.py'],'dd56773d0fb7e5df986301eaf873e03bd1124d31 seal; e952269 final evidence',RETAINED,'Per-seed fits and condition predictions retained; completed training comparison, exact missingness still structural.')
rr('R12: audio feasibility',AUDIO,[AUDIO+'/config.json'],[AUDIO+'/clock_metadata.json',AUDIO+'/segment_coverage.csv'],[SOURCES['R_AUDIO']],[FINAL+'/figures/13_audio_gate.pdf',FINAL+'/tables/08_audio_gate.csv'],['scripts/reassemble/18_completion_gates.py','scripts/reassemble/20_completion_synthesis.py'],'e952269bb34f29a239b0d6a267e1a53adc18acf7 final evidence',DOC,'A completed feasibility audit, not an audio-model result. No predictions/checkpoints should exist for unrun AST/trimodal experiments.')
rr('R13: physical-object OOD feasibility',OBJ,[OBJ+'/config.json'],[],[SOURCES['R_OBJECT']],[SOURCES['R_OBJECT_REPORT']],['scripts/reassemble/18_completion_gates.py'],'e952269bb34f29a239b0d6a267e1a53adc18acf7 final evidence',DOC,'Graph/identity evidence retained; no admissible physical-instance OOD predictions or trained OOD models.')
rr('R15/R16: efficiency and modularity',EFF,[EFF+'/config.json'],[EFF+'/results.json'],[SOURCES['R_EFF']],[FINAL+'/figures/12_efficiency.pdf',FINAL+'/tables/09_efficiency.csv'],['scripts/reassemble/19_completion_efficiency.py','scripts/reassemble/20_completion_synthesis.py'],'e952269bb34f29a239b0d6a267e1a53adc18acf7 final evidence',RETAINED,'Retained component repetitions permit aggregation, not identical hardware timing. No inference benchmark rerun during this freeze.')
rr('E01/E02/E03: completed exploratory comparisons only',EX,['configs/reassemble/additional_improvements/execution.json'],[EX+'/01_temporal_visual/'+n+'_predictions.npz' for n in ['V-MEAN','V-TEMP','V-NOPOS']]+[EX+'/02_patchtst_training_budget/'+n+'_predictions.npz' for n in ['S-6','S-LONG']]+[EX+'/03_static_anchored_adaptation/predictions.npz'],paths('EX_VIS EX_SENSOR EX_GATE'),[EX+'/'+d+'/comparison/metrics.csv' for d in ['01_temporal_visual','02_patchtst_training_budget','03_static_anchored_adaptation']],['scripts/thesis/build_final_documentation.py'],'8d4e7a9378cb51ffc3cd7b9be1e2785efc02d792 documentation-start HEAD; comparison source identity remains in extension manifests',DOC,'Metric JSON snapshots are hashed here; this freeze does not seal the ongoing extension. Fine-tuning, hybrid and repeated-corruption refinements are not accepted as final results here. No final combined winner model.')
rr('I01: Intel audit/no-go','artifacts/intel_welding/audits/foundation_runs/20260927T114705163655Z',[SOURCES['RQ']],[],[SOURCES['INTEL']],[SOURCES['INTEL']],[],'Read-only report identity in source manifest; no new model execution commit asserted',DOC,'Completed session/exposure audit, not a trained Intel model result; no protected replacement holdout was established.')
rr('Approved exposé / external PHM master Reasoning Record','unlocated',[],[],[],[],[], 'Unverified',MISSING,'Accessible local document names, attachments, repository references and Git history were searched. RQ is only a repository proxy; exact original compliance and external-record reconciliation await the originals.')

ABSTRACT=['P01','R01','R05','R07','R08']
CONCLUSION=['P01','P02','P06','R01','R05','R07','R08','R14']
LIMITATIONS=['P02','P03','P05','P06','P07','P08','I01','R03','R04','R06','R07','R08','R10','R11','R12','R13','R15','R16','E01','E02','E03']


def validate_sources():
 """Lightweight, read-only integrity and retained-prediction checks."""
 from importlib.metadata import version, PackageNotFoundError
 checks={}
 all_paths=set(SOURCES.values())|{str(CFG),config['request_source'],'scripts/thesis/build_final_documentation.py','src/reassemble/section1_features.py',S1+'/pretrained_model.json','../datasets/REASSEMBLE/cache/section1_models/ac77a11ff0170a41b771c03264987f8ce2b0d753/config.json'}
 for row in REPRO:
  for key in ['configs','predictions_or_observations','metric_sources','figures_or_tables','scripts']:
   all_paths.update(row[key])
 all_paths.update(['artifacts/reassemble/audits/nested_splits.json',S1+'/nested_splits.json',S1+'/cohort.parquet','runs/reassemble/20260927T141645Z-inventory/recordings.parquet','runs/reassemble/20260927T134437Z/official_record.json','runs/reassemble/20260927T134437Z/acquisition.json','artifacts/phm2026/raw_data_manifest.json'])
 for base in [P,T]:
  all_paths.update(str(p) for p in (Path(base)/'manifests').glob('*.json'))
  all_paths.add(base+'/provenance.json')
 for base in [S1,S1B,S2,S3,DROP,AUDIO,EFF,OBJ,FINAL]:
  all_paths.update(str(p) for p in Path(base).glob('*manifest.json'))
  for name in ['implementation.json','training_implementation.json','provenance.json','seal.json']:
   if Path(base,name).exists(): all_paths.add(str(Path(base,name)))
 figs=read(SOURCES['R_FIGURES'])
 for fig in figs: all_paths.update(fig['outputs']+fig['sources']+[fig['script']])
 all_paths.update(str(p) for p in Path(FINAL,'tables').glob('*'))
 source_inventory=[]
 for p in sorted(all_paths):
  f=Path(p);assert f.exists(),f'Missing referenced source: {p}'
  source_inventory.append({'path':p,'type':'directory' if f.is_dir() else 'file','size_bytes':None if f.is_dir() else f.stat().st_size,'sha256':None if f.is_dir() else sha(f)})
 checks['source_files_exist']=True
 checks['source_inventory']=source_inventory
 configs=sorted({p for row in REPRO for p in row['configs'] if Path(p).suffix in {'.json','.yaml','.yml'}})
 for p in configs:
  if p.endswith('.json'): read(p)
  else: yaml.safe_load(Path(p).read_text())
 checks['parsed_configs']=configs
 manifest_checks=[]
 for base in [P,T]:
  mp=Path(base,'manifests/outputs.json');items=read(mp)['artifacts']
  for item in items:
   p=Path(base,item['path']);assert p.is_file(),str(p)
   assert p.stat().st_size==item['size_bytes'],str(p)
   assert sha(p)==item['sha256'],str(p)
  manifest_checks.append({'path':str(mp),'entries_verified':len(items)})
 checks['PHM_output_manifests']=manifest_checks
 # Actual feature/target inputs override stale descriptive strings in the old config.
 resolved=yaml.safe_load(Path(P,'config/resolved_config.yaml').read_text())
 input_checks=[]
 for entry in resolved['source_runs'].values():
  for rel,expected in entry['artifacts'].items():
   path=Path(entry['directory'],rel);actual=sha(path);assert actual==expected,str(path)
   input_checks.append({'path':str(path),'sha256':actual})
 checks['PHM_resolved_input_identities']=input_checks
 target=pd.read_parquet(Path(T,'tables/run_damage_targets.parquet'))
 pred=pd.read_parquet(Path(P,'tables/loeo_predictions.parquet'))
 report=read(SOURCES['P_LOEO'])
 phm_metrics=[]
 for row in report['summary']:
  q=pred[pred.model.eq(row['model'])]
  mae=float(np.abs(q.y_pred-q.y_true).mean());rmse=float(np.sqrt(np.mean((q.y_pred-q.y_true)**2)))
  assert np.isclose(mae,row['mae'],atol=1e-12,rtol=0)
  assert np.isclose(rmse,row['rmse'],atol=1e-12,rtol=0)
  for r in q.itertuples():
   t=target[(target.experiment==r.experiment)&(target.run==r.run)]
   assert len(t)==1 and np.isclose(t.iloc[0]['raw_top3_mean_pct'],r.y_true,rtol=0,atol=1e-12)
   if row['model']!='rtdetr_r4_image_NOT_loeo':assert r.fold==r.experiment
  phm_metrics.append({'model':row['model'],'n_runs':len(q),'MAE':mae,'RMSE':rmse})
 checks['PHM_retained_metric_recomputation']=phm_metrics
 checks['PHM_v3_target_matches_all_retained_predictions']=True
 # Verify semantic and byte identity; no rewrite of historical split metadata.
 splits=read('artifacts/reassemble/audits/nested_splits.json')
 semantic=hashlib.sha256(json.dumps({k:v for k,v in splits.items() if k!='sha256'},sort_keys=True).encode()).hexdigest()
 assert semantic==splits['sha256']
 assert sha('artifacts/reassemble/audits/nested_splits.json')==sha(S1+'/nested_splits.json')
 frame=pd.read_parquet(Path(S1,'cohort.parquet'))
 groups=set(frame.recording_id);seen=set();fold=np.full(len(frame),-1)
 for s in splits['folds']:
  train,test=set(s['train_recordings']),set(s['test_recordings'])
  assert not train&test and train|test==groups and not seen&test
  seen|=test;fold[frame.recording_id.isin(test)]=s['fold'];inners=set()
  for inner in s['inner']:
   it,iv=set(inner['train_recordings']),set(inner['validation_recordings'])
   assert not it&iv and it|iv==train and not inners&iv;inners|=iv
  assert inners==train
 assert seen==groups and len(frame)==4530 and frame.failure.sum()==509 and len(groups)==148
 checks['REASSEMBLE_split']={'file_SHA256':sha('artifacts/reassemble/audits/nested_splits.json'),'canonical_content_SHA256':semantic,'canonical_algorithm':'SHA256(json.dumps(unsigned_split_object, sort_keys=True).encode()); excludes sha256 member','cohort_SHA256':sha(S1+'/cohort.parquet'),'segments':len(frame),'failures':int(frame.failure.sum()),'recordings':len(groups),'fold_segments':np.bincount(fold).tolist(),'train_test_and_inner_disjoint':True}
 core=read(SOURCES['R_S1']);s2=read(SOURCES['R_S2']);s1b=read(SOURCES['R_S1B']);s3=read(SOURCES['R_S3']);drop=read(SOURCES['R_DROP'])
 metric_checks=[]
 def predcheck(path,models):
  with np.load(path,allow_pickle=False) as z:
   assert np.array_equal(z['y'],frame.failure.to_numpy()),path
   assert np.array_equal(z['fold'],fold),path
   for name,pkey,expected in models:
    ap=float(average_precision_score(z['y'],z[pkey]));auc=float(roc_auc_score(z['y'],z[pkey]))
    assert abs(ap-expected['AUPRC']['estimate'])<1e-12,(path,name,'AP')
    assert abs(auc-expected['AUROC']['estimate'])<1e-12,(path,name,'AUROC')
    metric_checks.append({'path':path,'model':name,'AP':ap,'AUROC':auc,'folds_and_labels_match':True})
 for m in ['sensor_statistics','patchtst','rtdetr']:
  predcheck(S1+'/predictions/'+m+'_perm00.npz',[(m,'p',core['metrics'][m])])
 predcheck(S1B+'/stacking/oof.npz',[('F2','p',s1b['metrics']['minimal_late_fusion'])])
 predcheck(S2+'/predictions/oof.npz',[(m,m+'_p',v) for m,v in s2['metrics'].items()])
 predcheck(DROP+'/predictions/clean.npz',[('dropout_F6','p',drop['conditions']['clean']['metrics'])])
 for s in splits['folds']:
  with np.load(S1B+f"/stacking/outer{s['fold']}.npz",allow_pickle=False) as z:
   assert np.array_equal(z['test_rows'],np.flatnonzero(fold==s['fold']))
   assert np.array_equal(z['train_rows'],np.flatnonzero(fold!=s['fold']))
   assert z['training_branch_oof'].shape==(len(z['train_rows']),2)
 checks['REASSEMBLE_metric_recomputation']=metric_checks
 checks['Section1B_stacker_train_test_indices_match']=True
 checks['Section1B_outer_fold_deltas']=s1b['outer_fold_differences']
 checks['Section1B_leave_one_fold_out_deltas']=s1b['leave_one_outer_fold_out_differences']
 checks['complementarity']=s1b['complementarity']
 checks['sensor_permutation']=s1b['sensor_permutation']
 checks['figure_outputs_and_scripts_exist']=len(figs)
 checks['visual_backbone_identity']={'model_type':read('../datasets/REASSEMBLE/cache/section1_models/ac77a11ff0170a41b771c03264987f8ce2b0d753/config.json')['backbone_config']['model_type'],'implementation':'src/reassemble/section1_features.py: load_visual returns .model.backbone.model; Transformer encoder/decoder not used in core feature extraction.'}
 checks['preservation']=read(RUN/'preservation_before.json');assert checks['preservation']['passed']
 checks['environment_packages']={}
 for p in ['numpy','pandas','scipy','scikit-learn','torch','transformers','pyarrow','h5py','opencv-python','PyYAML']:
  try: checks['environment_packages'][p]=version(p)
  except PackageNotFoundError: checks['environment_packages'][p]='not installed under this distribution name'
 checks['bootstrap_scope']='Existing CI JSONs and manifests verified; no bootstrap, permutations, training, corruption generation, or figure rendering rerun.'
 checks['historical_nonstandard_JSON']='PROFILE_DIAGNOSTICS_V3.json includes NaN tokens; preserved unchanged. New outputs use strict JSON (allow_nan=False).'
 checks['git_diff_check']=subprocess.run(['git','diff','--check'],capture_output=True,text=True).__dict__
 checks['git_diff_check']={k:checks['git_diff_check'][k] for k in ['args','returncode','stdout','stderr']}
 assert checks['git_diff_check']['returncode']==0
 pip=subprocess.run([sys.executable,'-B','-m','pip','check'],capture_output=True,text=True)
 checks['pip_check']={'returncode':pip.returncode,'stdout':pip.stdout.strip(),'stderr':pip.stderr.strip()};assert pip.returncode==0
 return checks


def main():
 parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--resume',action='store_true',help='Regenerate only this documentation run’s owned files.');args=parser.parse_args()
 outputs=['docs/thesis/EXPOSE_TO_FINAL_THESIS_MATRIX.md','artifacts/thesis/EXPOSE_COMPLIANCE_SUMMARY.json','docs/thesis/FINAL_CLAIM_MATRIX.md','artifacts/thesis/final_claim_matrix.csv','docs/thesis/FINAL_THESIS_REPRODUCIBILITY.md','artifacts/thesis/FINAL_REPRODUCIBILITY_AUDIT.json']
 owner=RUN/'documentation_owner.json'
 if any(Path(p).exists() for p in outputs):
  if not args.resume or not owner.exists() or read(owner).get('outputs')!=outputs:raise SystemExit('Refusing to overwrite existing documentation; explicit same-run --resume and owner record required.')
 RUN.mkdir(parents=True,exist_ok=True)
 if not owner.exists():owner.write_text(dump({'outputs':outputs,'run':str(RUN)}))
 statuses={'ANSWERED','PARTIALLY ANSWERED','ADAPTED','NOT RUN — GATE FAILED','SUPERSEDED'}
 assert all(r['status'] in statuses for r in COMPLIANCE)
 assert len({c['claim_id'] for c in CLAIMS})==len(CLAIMS)
 assert len(ABSTRACT)<=5 and len(CONCLUSION)<=8
 checks=validate_sources()
 start=read(RUN/'preflight.json')
 freeze={'timestamp_UTC':datetime.now(timezone.utc).isoformat(),'git_commit':subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip(),'git_status':subprocess.check_output(['git','status','--short','--branch','--untracked-files=all'],text=True),'git_diff_stat':subprocess.check_output(['git','diff','--stat'],text=True),'command':'PYTHONPATH=src ma_thesis_env/bin/python -B scripts/thesis/build_final_documentation.py'+(' --resume' if args.resume else ''),'documentation_run':str(RUN),'start_environment':start}
 # Source IDs are expanded to actual paths in all machine-readable rows.
 preface='Snapshot: '+freeze['timestamp_UTC']+'. Documentation-only run: `'+str(RUN)+'`. Completed experiments and external records were not edited. Previously authorized extension jobs remain separate.\n\n'
 caveat=('The approved original exposé and external PHM master Reasoning Record were not located after the user requested a local search. '
         'This is a **provisional correspondence matrix, not certification of compliance with the approved exposé**. '
         'The quoted Main RQ and paraphrased SQ intentions use '+link(SOURCES['RQ'])+' as a repository proxy. '
         'Other intentions are explicitly inferred from retained task/evidence records. No supervisor approval is inferred. '
         'Search scope and exclusions: '+link(str(RUN/'original_document_search.json'))+'.\n\n')
 headers=['Original exposé item','Original wording / intention (proxy, not verified approved text)','Final implemented form','Dataset','Experiment / method','Main evidence','Status','Reason for deviation','Thesis-safe interpretation','Remaining limitation','Artifact/source path','Suggested chapter']
 rows=[]
 for r in COMPLIANCE:
  rows.append([r[k] if k!='source_paths' else '; '.join(link(p) for p in r[k]) for k in r])
 assessment={
  'conceptual_continuity':'Design and evaluate process-aware multimodal industrial prediction using strong unimodal baselines, modular fusion, robustness interventions and evaluation beyond accuracy. A negative answer is still an answer to a research question.',
  'methodological_changes':'PHM became provisional image-target regression and bounded sensor diagnostics; Intel was stopped at the evaluation-protection gate; REASSEMBLE added recording-disjoint annotated failure classification. RT-DETR became a frozen ResNet-backbone representation (its Transformer encoder/decoder was unused in the core), statistics replaced the tested PatchTST in core fusion, logistic stacking replaced the planned convex combination, and scalar late gates replaced any implied temporal cross-attention. The standalone gate was explicitly replaced by an incremental-information gate for Section 1B.',
  'gated_exclusions':'Intel new models; audio/AST/trimodal/audio-corruption experiments; physical-object OOD; dependent PHM sensor stages after failed signal gates. None is a poor model result.',
  'SQ1':'Partially answerable across the full original modality scope: visual and sensor representations tested with bounded conclusions; audio suitability unanswered.',
  'SQ2':'Answerable for the tested visual/sensor family: static late fusion improves beyond statistics; original gates do not establish additional clean gain. Full originally contemplated trimodal or temporal-cross-attention scope not evaluated.',
  'SQ3':'Answerable with a bounded negative for the original core gates and mixed dropout results under the declared faults. Complete-loss fallback is structural. Audio, natural faults and physical-object OOD remain outside evaluated scope.',
  'SQ4':'Partially answerable: predictive/calibration metrics, component cost and diagnostics measured; human interpretability, branch replacement generalization and prospective usability untested.',
  'useful_supervisor_acknowledgement':'Reconcile each row with the actual approved exposé and external master when available; acknowledge the dataset/task pivots, statistics selection, representation-not-detection use, logistic late fusion, gated exclusions, exploratory status, and separate appendix treatment of later positive adaptive results. This package does not assert that acknowledgement has occurred.',
 }
 md='# Exposé to final thesis correspondence\n\n'+preface+caveat+table(headers,rows)+'## Overall compliance assessment\n\n'
 for k,v in assessment.items():md+='**'+k.replace('_',' ').capitalize()+':** '+v+'\n\n'
 md+='The conceptual continuity is supported by the repository evidence; exact approved-exposé compliance remains unverified until the missing originals are reconciled.\n'
 Path(outputs[0]).write_text(md)
 Path(outputs[1]).write_text(dump({'schema_version':1,'snapshot':freeze['timestamp_UTC'],'run':str(RUN),'original_expose_verified':False,'external_master_reviewed':False,'proxy_source':SOURCES['RQ'],'search_record':str(RUN/'original_document_search.json'),'status_counts':dict(Counter(r['status'] for r in COMPLIANCE)),'rows':COMPLIANCE,'overall_assessment':assessment}))

 md='# Final combined thesis claim ledger\n\n'+preface
 md+='This ledger governs proposed thesis wording at this snapshot. It does not revise historical reports. “Current” means eligible within its bounded study scope; “exploratory” denotes separately labelled later comparisons. Historical entries require their original protocol labels; retired entries identify overstatements or numbers ineligible as current headlines. Missing experiments are not performance results.\n\n'
 md+='PHM-P: '+P_PROTOCOL+'\n\nREAS-R: '+R_PROTOCOL+' Intervals condition on fitted predictions and do not cover all architecture-selection or training uncertainty. Seeds are not additional independent recording samples.\n\n'
 md+='Point estimates below are rounded for reading; linked machine-readable result sources retain full precision. Differences are challenger minus reference; lower MAE/Brier/ECE is better. “AUPRC” in this repository is average precision. The oracle overlap is descriptive only.\n\n'
 ch=['Claim ID','Exact proposed thesis sentence','Study','RQ/SQ','Evidence','Point estimate','Uncertainty','Evaluation protocol','Artifact path','Evidence status','Important limitation','Allowed wording','Overstatement to avoid','Placement','Current / exploratory / historical / retired']
 for label,selected in [('PHM and evaluation design',[x for x in CLAIMS if x['claim_id'].startswith(('P','I'))]),('Completed REASSEMBLE core',[x for x in CLAIMS if x['claim_id'].startswith('R')]),('Separate exploratory extension',[x for x in CLAIMS if x['claim_id'].startswith('E')]),('Retired claims and guardrails',[x for x in CLAIMS if x['claim_id'].startswith('X')])]:
  md+='## '+label+'\n\n'
  md+=table(ch,[[v if k!='artifact_paths' else '; '.join(link(p) for p in v) for k,v in row.items()] for row in selected])
 byid={r['claim_id']:r for r in CLAIMS}
 for title,ids in [('Claims suitable for Abstract (maximum 5)',ABSTRACT),('Claims suitable for Conclusion (maximum 8)',CONCLUSION)]:
  md+='## '+title+'\n\n'+''.join('- **'+cid+'**: '+byid[cid]['exact_proposed_thesis_sentence']+'\n' for cid in ids)+'\n'
 md+='## Claims that must remain in Limitations\n\n'
 md+='A shortened thesis must retain the qualifications attached to '+', '.join(LIMITATIONS)+'. In particular: provisional PHM target and exposed history; small clustered samples; bounded feature/model budgets; outcome-informed reuse of REASSEMBLE folds; one core corruption realization per condition; no audio, physical-object OOD or prospective deployment study; and component timing rather than production latency. The original exposé and external Reasoning Record remain unavailable.\n\n'
 md+='## Retired claims that must never reappear\n\n'
 md+='- PHM sensors contain no information, or the synthetic control proves absence of real signal.\n- Changing weights proves the gate understands reliability; flat degradation proves robustness.\n- Failed audio/OOD/Intel feasibility means those models performed poorly.\n- The historical EXP-F split is an untouched final test; the R4 image reference is a LOEO visual result.\n- All adaptive architectures fail: this is incompatible with the separate positive exploratory E03 comparison.\n- Old target/split values in X01 are current v3 LOEO results, or a literal paired empirical ΔMAE equals its stored bootstrap-mean estimator.\n- Oracle correctness is deployable performance, classification AP is detection AP, or three fusion parameters describe the entire model.\n\n'
 md+='## Failure and action-specific complementarity (support for R04)\n\n'
 comp=checks['complementarity']
 md+=table(['Subset','n','Both correct','Both wrong','Visual only correct','Sensor only correct','Score correlation','Error correlation','Oracle correct fraction'],[[k,v['segments'],v['both_correct'],v['both_wrong'],v['visual_only_correct'],v['sensor_only_correct'],f"{v['prediction_correlation']:.4f}",f"{v['error_correlation']:.4f}",f"{v['oracle_correct_fraction']:.4f}"] for k,v in comp.items()])
 md+='This is a transcription of Section 1B diagnostics, not a new fitted analysis. Place has only 22 failures; no action-uniform incremental gain is asserted.\n'
 Path(outputs[2]).write_text(md)
 buf=io.StringIO();w=csv.DictWriter(buf,fieldnames=list(CLAIMS[0]));w.writeheader()
 for row in CLAIMS:w.writerow({k:json.dumps(v,ensure_ascii=False) if isinstance(v,list) else v for k,v in row.items()})
 Path(outputs[3]).write_text(buf.getvalue())

 gaps=[
  'Approved original exposé and external PHM master Reasoning Record unlocated; correspondence provisional.',
  'PHM raw archives absent after authorized retirement; recovery requires re-download, not performed here.',
  'Synthetic positive-control and PHM sensor-fusion per-run predictions/checkpoints not identified; numerical retraining reproduction is not claimed.',
  'PHM LOEO snapshot contains stale v2/fixed-split descriptive fields; verified input artifacts are v3 and evaluator/results implement LOEO. Preserve and disclose, do not silently rewrite.',
  'PHM stored paired ΔMAE is a bootstrap-mean estimator, distinct from the direct difference of displayed MAEs.',
  'No independent full-training reproduction, prospective deployment validation or fresh untouched final holdout supplied by this documentation task.',
  'Exploratory extension remains active outside this freeze; completed subcomparisons do not mean all four tasks finished.',
  'Current working tree is not clean: active extension status files and pre-existing unrelated work coexist with new documentation; hashes freeze this package, not the entire moving workspace.',
 ]
 audit={'schema_version':1,'status':'THESIS REPRODUCIBILITY PACKAGE READY WITH DOCUMENTED GAPS','freeze':freeze,'headline_results':REPRO,'gaps':gaps,'checks':checks,'claims_abstract':ABSTRACT,'claims_conclusion':CONCLUSION,'source_registry':SOURCES,'source_search':str(RUN/'original_document_search.json'),'documentation_scope':'Only retained-evidence checks and documentation; no new model fitting, raw downloads, raw edits, deletions or historical result changes.'}
 md='# Final thesis reproducibility freeze\n\n'+preface+'**'+audit['status']+'**\n\n'
 md+='The retained-artifact status below means that the specific reported result can be checked from saved predictions, observations or aggregates, as qualified in each row. It does not claim bitwise independent model retraining or identical latency on different hardware. Existing bootstrap intervals are linked and hash-verified; no expensive experiment or bootstrap was rerun.\n\n'
 md+='## Repository and environment\n\n'
 md+='Documentation-start and validation HEAD: `'+freeze['git_commit']+'`. The tree is dirty; full before/validation status, command, environment and diff summary are retained in '+link(str(RUN/'preflight.json'))+' and '+link(outputs[5])+'. No commit was made by this documentation task. The documentation generator/config/source hashes identify this uncommitted package.\n\n'
 md+='Python '+str(start['python'])+'; Torch '+str(start['torch'])+'; Torch CUDA '+str(start['torch_cuda'])+'. GPU snapshot: `'+str(start['GPU']).replace('\n','; ')+'`. These are the available environment identities, not a claim that the documentation task used a GPU. Historical run provenance remains authoritative for each experiment.\n\n'
 md+=table(['Package','Version'],checks['environment_packages'].items())
 md+='Full environment preflight: '+link(str(RUN/'preflight.json'))+'. Package dependency check: '+checks['pip_check']['stdout'].rstrip('.')+'.\n\n'
 md+='## Dataset, target and split identities\n\n'
 md+='PHM scope: EXP-A runs 1–5, EXP-B 1–7, EXP-F 1–8. Original root `gtc-data-experiment/` is absent after the separately approved retirement. The immutable raw manifest '+link('artifacts/phm2026/raw_data_manifest.json')+' has SHA256 `'+sha('artifacts/phm2026/raw_data_manifest.json')+'`. It covers 53 files (52 official archives plus a helper); the recorded logical payload total is 381481909715 bytes. EXP-A Run 2’s organizer warning concerns 311 overlaps with Run 1: preserve that source warning; no raw deduplication was done here. Target/feature tables retain run identity.\n\n'
 md+='Recovery is documented in '+link(SOURCES['P_RECOVERY'])+' and '+link(SOURCES['P_RETIREMENT'])+' with portable configuration `configs/phm2026/download_manifest.json` and downloader `src/phm2026/acquisition/phm_download.py`. A future authorized recovery command is `ma_thesis_env/bin/python -B download.py --experiments A B F`; **it was not executed here**. Recorded remote-inventory and prefix checks were historical tests, not a fresh availability guarantee. No credentials or session contents were read.\n\n'
 md+='PHM current target: `phm2026_image_damage_v3`, one deterministic image for each of teeth 5–28, worst-three mean `raw_top3_mean_pct`, 20 run-level targets / 480 tooth-run rows. Current target source is `'+T+'`. Full version exclusions: '+link(SOURCES['P_TARGET'])+'. The LOEO config retains stale `definition_version: phm2026_image_damage_v2` and fixed EXP-B/A/F split fields; the linked source-run hash points to the v3 target, which matches every retained prediction label, and the evaluator/report implements the three LOEO folds. These are disclosed historical metadata defects, not silently corrected files.\n\n'
 md+='REASSEMBLE root: `../datasets/REASSEMBLE`; raw recordings under `raw/data/`. Recorded official source: TU Wien record `0ewrv-8cb44`, DOI `10.48436/0ewrv-8cb44`; local evidence '+link('runs/reassemble/20260927T134437Z/official_record.json')+'. The recorded `data.zip` is 58881334586 bytes, MD5 `812103a652ca9201e87a3bcecfee4ef3`; acquisition metadata is '+link('runs/reassemble/20260927T134437Z/acquisition.json')+'. The 149-recording SHA256 inventory is '+link('runs/reassemble/20260927T141645Z-inventory/recordings.parquet')+'. No raw payload rehash or download was required for this freeze.\n\n'
 md+='Primary cohort: 4530 dual-complete pick/insert/remove/place segments, 509 failures, 148 recordings; hand camera, five sensor streams / 22 channels. The 149 raw recordings are not the number of included recording clusters. Cohort file: '+link(S1+'/cohort.parquet')+'; SHA256 `'+checks['REASSEMBLE_split']['cohort_SHA256']+'`.\n\n'
 md+='Frozen split file '+link('artifacts/reassemble/audits/nested_splits.json')+' and Section 1 copy have identical byte SHA256 `'+checks['REASSEMBLE_split']['file_SHA256']+'`. The embedded canonical-content hash is `'+checks['REASSEMBLE_split']['canonical_content_SHA256']+'`. The latter excludes the `sha256` member and uses sorted-key JSON serialization. The two hashes identify different serializations, not different folds. All five outer and four inner partitions were checked for recording disjointness and coverage; labels/folds agree across retained core predictions.\n\n'
 md+='PHM LOEO split identity is the explicit `folds` object in '+link(SOURCES['P_LOEO'])+' (source file SHA256 `'+sha(SOURCES['P_LOEO'])+'`): predict A using F training/B validation; predict B using F training/A validation; predict F using B training/A validation. The historical fixed-split manifest referenced in the resolved config does not redefine this evaluator’s LOEO loop. Current input artifact hashes were verified.\n\n'
 md+='Core visual scope: the pinned config identifies `rt_detr_resnet`; extraction returns `.model.backbone.model`. The detector’s Transformer encoder/decoder is unused. Pretrained source/weight identities are retained in `'+S1+'/pretrained_model.json`; this is a substantive SQ1 scope qualification.\n\n'
 md+='## Headline-to-artifact chain\n\n'
 rh=['Claim','Run','Config','Predictions / observations','Metric source','Figure / table','Generation scripts','Commit identity','Status','Limitation']
 def refs(v):return '; '.join(link(p) for p in v) if v else 'Not retained / not applicable; see status and limitation'
 md+=table(rh,[[r['claim'],r['run'],refs(r['configs']),refs(r['predictions_or_observations']),refs(r['metric_sources']),refs(r['figures_or_tables']),refs(r['scripts']),r['commit_identity'],r['status'],r['limitation']] for r in REPRO])
 md+='## Exact settings, seeds and uncertainty\n\n'
 protocols=[
 ['PHM LOEO','Resolved YAML in run; seed 20260814; max 80 epochs/patience 10/batch 4/lr .001/wd .0001; experiment-disjoint train/validation rule','10000 run-cluster paired draws with seed 20260814; 20 run units; stored paired point is bootstrap-mean Δ, not empirical Δ'],
 ['PHM signal','Script defaults and retained reports: 472 steady files, run-mean features, threshold |rho|≥.5','300 within-experiment run-label permutations, seed 20260912; empirical zero exceedances is not probability zero'],
 ['PHM synthetic','Code plus retained per-seed aggregate JSON; model seeds 1,2,3; deliberate target-aligned injection','10000 run-cluster draws; seed 20260912; missing predictions prevent metric-only independent reconstruction'],
 ['REASSEMBLE Section 1','config.json: base seed 20260927; RT-DETR revision ac77a11ff0170a41b771c03264987f8ce2b0d753; frozen 16×640 frames; head 5/10 epochs; PatchTST 3/6 epochs; statistics C [.1,1,10]','2000 recording draws; report RNG base+50000 = 20310927; 19 within-recording/action chronological circular shifts; complete inner procedure repeated'],
 ['REASSEMBLE Section 1B','Frozen branches; four deeper subfolds to generate outer-training branch OOF; C=1 unweighted logistic on two calibrated probabilities; no fit on outer-test OOF','2000 paired recording draws, RNG 20310927; .01 meaningful AP increment and AUROC noninferiority margin .01; null p minimum .05'],
 ['REASSEMBLE Section 2','Seeds 20260927/28/29; F3 hidden32×10ep or64×20ep; F4–F6 hidden8 or16×40ep; exact configs retained; probability clip1e−6','Three-seed mean predictions, fold/seed summaries; 2000 paired recording draws; marginal CIs plus Bonferroni lower AP bounds for three gate-vs-F2 claims'],
 ['Section 3 and dropout','Exact operators/severity/seed derivation in section3_corruptions.json; source pixels/raw sensors; frozen clean training/thresholds; dropout .15/.15/.70 with same three seeds','2000 paired recording draws, bootstrap seed20310927; one deterministic fault realization per core condition; complete loss adopts surviving branch threshold'],
 ['Calibration and thresholds','Unweighted sigmoid logistic on selected inner OOF logits; scaling fitted only to fitting subset; balanced-accuracy thresholds .01 through .99, tie nearest .5; F2 no extra output calibrator','Section1B meta-cross-fitted outer-training scores set threshold; ECE15 equal-width bins; AP uses sklearn average precision; all reported intervals conditional on retained models'],
 ]
 md+=table(['Evidence family','Configuration / fitting','Uncertainty / interpretation'],protocols)
 md+='Threshold values, hyperparameter selections, per-fold scores and seed variability are retained in Section 1 logs, Section 1B stacking JSONs, and `'+S2+'/assessment/selected_hyperparameters.json` plus `assessment/results.json`. Fold-specific checkpoints and hashes are enumerated in each run’s output manifest; no checkpoint was loaded or model retrained during this documentation task.\n\n'
 md+='## Figures, tables and executable provenance\n\n'
 md+='All 14 completed REASSEMBLE figures (PDF and PNG) are indexed with source paths, captions and chapters in '+link(SOURCES['R_FIGURES'])+'. Their generation entry point is '+link('scripts/reassemble/20_completion_synthesis.py')+' backed by '+link('src/reassemble/completion_synthesis.py')+'. Tables are in `'+FINAL+'/tables/`; exact paths and SHA256 identities are in the audit source inventory. PHM target figures are retained under `'+T+'/figures/`; their generator is '+link('scripts/phm2026/targets/derive_image_targets.py')+'. No figure was regenerated.\n\n'
 md+='Core source/checkpoint identity chains: Section 1 `training_implementation.json` and `final_output_manifest.json`; Section 1B/2 `implementation.json`, `inputs/`, fitted artifacts and `output_manifest.json`; completion `seal.json` and per-run manifests. Seal commit `dd56773d0fb7e5df986301eaf873e03bd1124d31` precedes final evidence commit `e952269bb34f29a239b0d6a267e1a53adc18acf7`; they are not competing experiment versions. Earlier final-synthesis formatting records remain archived in `review_correction_v2/`.\n\n'
 md+='## Lightweight validation performed\n\n'
 md+='- All referenced paths exist; JSON/YAML configs parse; source/report/config/prediction identities saved in the audit.\n- PHM target and LOEO output manifests and resolved source-run hashes match; MAE/RMSE and all prediction target labels agree with retained v3 data.\n- Core REASSEMBLE AP/AUROC rederive from retained scores; cohort labels, split membership and Section 1B stacker train/test indices agree. No new fit or resampling was required.\n- Prior Section 1/1B/2 and completed run manifests pass. Protected metadata: 68745 PHM/environment entries and 149 raw HDF5 identities unchanged; historical Git blob retained. Scope: SHA256 for completed evidence; size/mtime for raw payloads; not a new full raw-content audit.\n- Fourteen figure pairs and their source/script paths exist; package dependency and Git whitespace checks pass.\n- Documentation row counts/statuses and CSV/JSON concordance are checked by the generator.\n\n'
 md+='## Documented gaps and corrections\n\n'+''.join('- '+g+'\n' for g in gaps)+'\n'
 md+='The first local filename search overmatched parent directory names and was replaced by basename-filtered document discovery with environment/cache/session directories excluded. It read no credential/session contents. Expected absent files encountered during path discovery were resolved to actual artifacts (for example Section 1 uses `training_implementation.json`). The apparent split-hash discrepancy was resolved as byte versus canonical-content hashing. Historical JSON containing NaN is left unchanged; new JSON is strict. These documentation clarifications do not alter results.\n\n'
 md+='The CSV claim ledger is present locally but matches the repository’s existing global CSV ignore rule; no tracking policy was changed. Include it explicitly when exporting the package. A later IDE can continue from '+link('docs/thesis/DOCUMENTATION_CONTINUATION.md')+'. Before any future rebuild, create a new versioned documentation run or use the explicit same-run `--resume` only for corrections to this package. Do not rerun training/recovery/figure-generation commands just to reproduce these documents.\n\n**'+audit['status']+'**\n'
 Path(outputs[4]).write_text(md)
 Path(outputs[5]).write_text(dump(audit))
 # Concordance and preservation guard: compare every input byte hash after writing new docs.
 with Path(outputs[3]).open(newline='') as f:csvrows=list(csv.DictReader(f))
 assert [r['claim_id'] for r in csvrows]==[r['claim_id'] for r in CLAIMS]
 assert len(read(outputs[1])['rows'])==len(COMPLIANCE)
 for row in checks['source_inventory']:
  if row['sha256']: assert sha(row['path'])==row['sha256'],f"Source changed during build: {row['path']}"
 # The config/script are inputs and remain unchanged during a successful build.
 validation={'timestamp_UTC':freeze['timestamp_UTC'],'passed':True,'compliance_rows':len(COMPLIANCE),'claim_rows':len(CLAIMS),'headline_rows':len(REPRO),'abstract_claims':len(ABSTRACT),'conclusion_claims':len(CONCLUSION),'all_source_hashes_unchanged_after_documentation':True,'outputs':[]}
 for p in outputs:validation['outputs'].append({'path':p,'size_bytes':Path(p).stat().st_size,'sha256':sha(p)})
 (RUN/'documentation_validation.json').write_text(dump(validation))
 (RUN/'configuration_snapshot.json').write_text(dump(config))
 (RUN/'source_manifest.json').write_text(dump(checks['source_inventory']))
 print(dump({'status':audit['status'],'rows':{'compliance':len(COMPLIANCE),'claims':len(CLAIMS),'reproducibility':len(REPRO)},'source_entries':len(checks['source_inventory']),'validation':str(RUN/'documentation_validation.json')}))

if __name__=='__main__':main()
