"""Research-history and cross-study addenda; never edit the external master record."""
from pathlib import Path
from .completion_common import read
from .section1_report import table


def narratives(c,root,reports,s1,s1b,s2,robust,dropout,audio,objects,eff,sq,main_rq,robustness_answer,dropout_answer):
    from .completion_synthesis import save_text,fmt
    phm_path='runs/phm2026_loeo_evaluation/20260912T110848985882Z-e1911d4f/reports/loeo_summary.json'
    phm=read(phm_path);reg={row['model']:row for row in phm['summary']};delta=phm['paired_deltas_vs_constant']['fused_all_three']
    text='# Cross-study synthesis handoff\n\n## Central comparison\n\nThe comparison concerns **conditions for meaningful fusion**, not which dataset scored higher. PHM remains Study 1 and REASSEMBLE remains Study 2; neither is rewritten to create a cleaner success narrative.\n\n'
    text+='## Different targets require different metrics\n\n**Task-appropriate metrics differ across the two empirical studies because PHM is a continuous damage-estimation problem whereas REASSEMBLE is a binary execution-failure classification problem.**\n\nPHM uses MAE, RMSE where reported, Spearman/rank association and grouped paired uncertainty. REASSEMBLE uses AUROC, AUPRC, balanced accuracy, macro-F1, failure precision/recall, Brier and ECE. Never directly compare a numerical PHM MAE with REASSEMBLE AUROC, AP or F1. Improvements are interpreted within task against task-appropriate references.\n\n'
    text+='## PHM evidence available in this repository\n\nThe retained leave-one-experiment-out summary covers 20 runs from A/B/F and uses 10,000 run-cluster bootstrap draws. Its provisional damage-estimation target must not be called independently validated physical damage ground truth.\n\n'
    text+=table(['PHM model','MAE','MAE 95% interval','RMSE','Spearman'],[[m,f"{reg[m]['mae']:.4f}",f"[{reg[m]['mae_ci95_low']:.4f}, {reg[m]['mae_ci95_high']:.4f}]",f"{reg[m]['rmse']:.4f}",f"{reg[m]['spearman']:.4f}"] for m in ['constant_train_mean','patchtst_single_encoder','fused_all_three']])
    text+='\nThe stored paired fused-minus-constant difference is '+f"{delta['mean_delta_vs_constant']:.4f} [{delta['ci95_low']:.4f}, {delta['ci95_high']:.4f}]"+' on its run-weighted comparison, with no resolved benefit. Its paired estimator need not equal the difference of pooled displayed MAEs. Source: `'+phm_path+'`. The RT-DETR R4 image row is explicitly **NOT LOEO**, lacks EXP-B predictions and must not enter this grouped model ranking.\n\n'
    text+='Retained `docs/planning/HANDOFF.md` documents provisional photo-derived labels, run-level rather than verified UTC image/sensor pairing, only 20 run units, and deployment restricted to sensors. It is historical and partly superseded by later run artifacts: its statement that no fusion had occurred must not override the later LOEO summary. These sources substantiate target/independence/deployment caveats. Later external PHM reasoning about additional positive controls or corruption studies is not quantitatively reconstructed here without its exact artifacts. The importance of positive controls and the warning that flat low-signal degradation is not robustness are methodological conclusions, not invented PHM measurements.\n\n'
    text+='## REASSEMBLE evidence\n\nREASSEMBLE provides explicit execution outcomes, 148 recording groups and simultaneous visual/sensor measurements. Statistical sensors exceeded the tested temporal Transformer. Section 1B established visual complementarity and incremental static-fusion AP; Section 2 found no clean gain from additional gating. The predeclared corruption suite now supports this bounded SQ3 answer: '+robustness_answer+'\n\n'+dropout_answer+'\n\nAudio failed the segment-timing gate; the study did not force an AST result.\n\n'
    text+='## Conditions and implications\n\n1. Validate the target and independent evaluation units before optimizing architecture.\n2. Establish deployable modality informativeness and perform group-compatible controls.\n3. Establish incremental complementarity against the strongest unimodal reference.\n4. Prefer simple fusion when added complexity lacks supported benefit.\n5. Test unavailable and degraded modalities explicitly; report absolute performance as well as decline from clean performance.\n6. Require both induced allocation response and predictive benefit before calling a gate reliability-aware, and restrict that claim to the tested families.\n7. Preserve negative results, including architecture failure, timing-gate exclusion and structurally limited fallback.\n\n'
    text+='## Integration boundary\n\nThis addendum is intended for later integration with the researcher’s external master Reasoning Record. That record and historical PHM artifacts were not modified. Scene/day/object confounding, adaptive reuse of REASSEMBLE folds, artificial corruption and VM timing prevent broad deployment/generalization conclusions.\n'
    save_text(reports/'CROSS_STUDY_SYNTHESIS_HANDOFF.md',text)
    events=[
      ('PHM as the first study','Multimodal architectures might support continuous damage estimation.','Are target validity and deployable sensor information sufficient?','Fusion requires a defensible target and usable signals.','Retained provisional target audits, fixed/grouped evaluations and LOEO summary.','The grouped fusion comparison did not resolve benefit over a constant; only 20 runs support uncertainty.','Target and independent-unit constraints precede architecture claims.','[VERIFIED]','Keep PHM as Study 1; do not relabel its weak/uncertain evidence as success.'),
      ('Why a second study became useful','A second task could separate architecture questions from PHM target/deployment restrictions.','Can explicit labels and simultaneously available modalities support a clearer fusion test?','One constrained dataset cannot establish broad architecture suitability.','Select a complementary study with explicit outcomes and recording groups.','REASSEMBLE ultimately supplied these prerequisites.','The second study complements rather than erases PHM.','[VERIFIED]','Keep different task-appropriate metrics and avoid cross-task score rankings.'),
      ('Intel reconsideration','The local robotic-welding dataset might support the second study.','Are labels, grouping, modality availability and holdout status defensible?','Invalid foundations cannot be repaired by more training.','Read-only foundation audit; artifacts/intel_welding/audits/PHASE_1_GATE_REPORT.md.','The supplied split crossed 216/236 sessions; prior holdout exposure and selective missingness led to NO-GO.','Do not present exposed/context-confounded results as clean validation.','[NOT RUN — GATE FAILED]','Move to another foundation without rewriting Intel evidence.'),
      ('REASSEMBLE selection','Execution segments may support visual/sensor failure prediction.','Do coverage, labels and recording identity permit grouped evaluation?','Modality existence alone does not ensure usable multimodal support.','Foundation inventory, source identities, sensor/video quality and label audit.','The frozen primary cohort contains 4,530 segments, 509 failures, 148 usable recordings.','Visual+sensor modelling is feasible; audio requires a separate clock gate.','[VERIFIED]','Freeze cohort, labels and nested recording folds.'),
      ('Storage constraint and PHM retirement','Keeping all large raw datasets locally exceeded available disk.','Could PHM raw payloads be retired without losing recoverability or research evidence?','Storage pressure must not cause undocumented scientific data loss.','Previously user-authorized recovery manifest, official-source validation, bounded range test and protected-file audit.','Historical retirement recovered about 355.283 GiB; full SHA256 recovery specification and research outputs were preserved.','This was a specific historical authorization, not permission for new deletion.','[VERIFIED]','Retain recovery mechanism; current completion performs no deletion or redownload.'),
      ('Acquisition and foundation','Downloaded data could differ from nominal documentation.','Does the local copy match audited identities and support the intended task?','Reproducibility depends on local evidence, not assumed dataset claims.','Versioned acquisition/inventory and complete source provenance.','149 raw recordings inventoried; 148 enter the fixed primary cohort.','Use audited exclusions and exact source/run identity.','[VERIFIED]','Preserve raw data and immutable foundation artifacts.'),
      ('Section 1 representations','Named temporal/visual Transformers might be suitable primary branches.','Do their signals exceed context and simple statistical baselines?','Architecture preference must not substitute for predictive evidence.','Nested recording CV, action/prior baselines and group-compatible cyclic permutations.','Sensor statistics outperform tested PatchTST; visual AP adds context-relative signal but standalone AUROC improvement is unresolved.','The temporal Transformer hypothesis fails for this tested implementation, not all Transformers.','[FALSIFIED]','Retain PatchTST as a bounded SQ1 negative result; select sensor statistics.'),
      ('Section 1B admissibility','A weaker visual model could still add information beyond strong sensors.','Is visual information complementary and incrementally useful?','Standalone model rank does not answer fusion value.','Frozen OOF overlap plus strictly nested two-probability static stacking and clustered paired uncertainty.','97 visual-only correct failures across 61 recordings; positive static-fusion AP/AUROC increments.','Fusion warranted without changing the original standalone gate.','[VERIFIED]','Authorize a small clean-fusion comparison.'),
      ('Numerical reproduction correction','One BLAS thread was expected to reproduce the frozen sensor fit.','Does execution match the original probabilities?','Small numerical optimizer changes can invalidate claimed exact reuse.','Strict parity guard before permutation/fusion results.','The one-thread attempt failed; original 16-thread setting reproduced exactly.','Restore execution fidelity, not relax the scientific guard.','[CORRECTED]','Preserve failed attempt and use original threading.'),
      ('Section 2 clean fusion','Process/quality adaptation might improve static fusion.','Does extra complexity produce meaningful clean incremental value?','Mechanism plausibility requires an actual reference comparison.','F1–F6, three neural seeds, nested selection, paired intervals and context ablations.','No gate improves AP beyond F2; all lose AUROC. Context affects weights without proven clean benefit.','Simple fusion is sufficient within the tested comparison.','[FALSIFIED]','Retain static reference and bounded quality-capable gates for robustness testing.'),
      ('Shortlist interpretation correction','Highest gate AP point estimate could define the next candidate.','Do uncertainty, calibration, cost and stability support that ranking?','Point-only winner selection exaggerates weak differences.','Post-hoc descriptive review contrasts; preserve original generator output.','Section 2 reviewed shortlist preferred a simpler F4 mechanism control; current autonomous prompt explicitly authorizes F5/F6 for reliability testing.','Different mechanism questions justify the declared shortlist, not a hidden retuning step.','[CORRECTED]','Use current preregistered robustness shortlist; preserve both historical recommendations.'),
      ('Section 3 robustness','Quality-capable gates may help when a modality degrades.','Do induced weight shifts coincide with better predictive resilience?','Weight variability alone is not reliability awareness.','Predeclared raw/pixel corruptions, frozen models, 2,000 paired recording bootstrap draws and missing-modality parity.',robustness_answer,'Separate family-specific relative resilience from absolute corrupted performance.','[VERIFIED]','Use only bounded claims supported by the mechanism/outcome table.'),
      ('Modality dropout','Missingness training might improve gate robustness.','Can this exact architecture benefit without new branch information?','A fixed surviving-branch output places a structural limit on training.','One F6 variant, .15/.15/.70 masks, frozen architecture/branches, same folds and three seeds.',dropout_answer,'Joint-present behavior may change; complete-loss outputs cannot.','[VERIFIED]','Do not redesign the gate to rescue a negative hypothesis.'),
      ('Audio feasibility','Audio might provide further complementary signal.','Can the correct waveform interval be assigned to each action segment?','AST needs trustworthy segment boundaries, not frame-perfect synchrony.','Clock/header/coverage audit using immutable full-decoding evidence.',audio['decision'],'This is a timing/coverage exclusion, not evidence that audio lacks signal.','[NOT RUN — GATE FAILED]','Skip AST, tri-modal and audio-corruption training; continue synthesis.'),
      ('Object generalization','Object annotations might support unfamiliar-object evaluation.','Are physical identities and disjoint groups reliable?','A category label and repeated board context can masquerade as OOD evaluation.','Object support and recording/object connectivity audit.',objects['reason'],'Do not invent independent physical objects or degenerate folds.','[NOT RUN — GATE FAILED]','No object-generalization claim; retain as optional future data-design work.'),
      ('Efficiency and practical use','A small fusion head might make the whole system cheap.','Where do preprocessing, extraction and fusion costs actually occur?','Cached-head latency is not complete system latency.','Repeated warm component measurements after warmup; parameter/checkpoint/memory inventory.','Machine-readable results separate branch preprocessing, visual extraction and small fusion overhead.','VM sequential component sums are estimates, not production real-time certification.','[VERIFIED]','Frame deployment claims around measured components and missingness behavior.'),
      ('Final synthesis','The thesis should connect prerequisites, architecture and failure modes.','What do both studies jointly support?','Negative results are part of the answer, not reasons to keep searching.', 'Machine-linked tables/figures, SQ1–SQ4 answers, claim audit and preservation checks.',main_rq,'Use task-appropriate evidence and retain uncertainty, adaptivity and generalization limits.','[VERIFIED]','Close the study after final validation; leave only optional future work.')]
    story='# Thesis storyline addendum\n\nChronological reasoning narrative for later integration into the external master record. That record was not edited.\n\n'
    for title,*values in events:
        story+='## '+title+'\n\n'
        for name,value in zip(['ASSUMPTION','QUESTION','WHY IT MATTERED','METHOD','RESULT','INTERPRETATION','STATUS','CONSEQUENCE'],values):story+='**'+name+':** '+value+'\n\n'
    story+='## Source history\n\n- `artifacts/phm2026/PHM_RAW_RETIREMENT_REPORT.md` and `docs/phm2026/RAW_DATA_RECOVERY.md`.\n- `artifacts/intel_welding/audits/PHASE_1_GATE_REPORT.md` (retained earlier foundation evidence).\n- Original REASSEMBLE acquisition/foundation run `runs/reassemble/20260927T141645Z-inventory`.\n- Frozen Section 1, 1B and 2 handoffs; new Section 3 and modality-dropout handoffs.\n- `FINAL_REASSEMBLE_HANDOFF.md`, `FINAL_EVIDENCE_MAP.md` and the final output manifest.\n'
    save_text(reports/'THESIS_STORYLINE_ADDENDUM.md',story)
